package grest.youtubereporting.v1.types;
@:enum abstract GdataMedia_referenceType(String) from String to String to tink.Stringly {
	var ARBITRARY_BYTES = "ARBITRARY_BYTES";
	var BIGSTORE_REF = "BIGSTORE_REF";
	var BLOB_REF = "BLOB_REF";
	var COMPOSITE_MEDIA = "COMPOSITE_MEDIA";
	var COSMO_BINARY_REFERENCE = "COSMO_BINARY_REFERENCE";
	var DIFF_CHECKSUMS_RESPONSE = "DIFF_CHECKSUMS_RESPONSE";
	var DIFF_DOWNLOAD_RESPONSE = "DIFF_DOWNLOAD_RESPONSE";
	var DIFF_UPLOAD_REQUEST = "DIFF_UPLOAD_REQUEST";
	var DIFF_UPLOAD_RESPONSE = "DIFF_UPLOAD_RESPONSE";
	var DIFF_VERSION_RESPONSE = "DIFF_VERSION_RESPONSE";
	var GET_MEDIA = "GET_MEDIA";
	var INLINE = "INLINE";
	var PATH = "PATH";
}