package grest.genomics.v2alpha1.types;
typedef DelayedEvent = {
	/**
		A textual description of the cause of the delay. The string can change without notice because it is often generated by another service (such as Compute Engine).
	**/
	@:optional
	var cause : String;
	/**
		If the delay was caused by a resource shortage, this field lists the Compute Engine metrics that are preventing this operation from running (for example, `CPUS` or `INSTANCES`). If the particular metric is not known, a single `UNKNOWN` metric will be present.
	**/
	@:optional
	var metrics : Array<String>;
}