package grest.spanner.v1.types;
@:enum abstract RestoreDatabaseEncryptionConfig_encryptionType(String) from String to String to tink.Stringly {
	var CUSTOMER_MANAGED_ENCRYPTION = "CUSTOMER_MANAGED_ENCRYPTION";
	var ENCRYPTION_TYPE_UNSPECIFIED = "ENCRYPTION_TYPE_UNSPECIFIED";
	var GOOGLE_DEFAULT_ENCRYPTION = "GOOGLE_DEFAULT_ENCRYPTION";
	var USE_CONFIG_DEFAULT_OR_BACKUP_ENCRYPTION = "USE_CONFIG_DEFAULT_OR_BACKUP_ENCRYPTION";
}