package grest.networkmanagement.v1.types;
@:enum abstract RouteInfo_nextHopType(String) from String to String to tink.Stringly {
	var NEXT_HOP_BLACKHOLE = "NEXT_HOP_BLACKHOLE";
	var NEXT_HOP_ILB = "NEXT_HOP_ILB";
	var NEXT_HOP_INSTANCE = "NEXT_HOP_INSTANCE";
	var NEXT_HOP_INTERCONNECT = "NEXT_HOP_INTERCONNECT";
	var NEXT_HOP_INTERNET_GATEWAY = "NEXT_HOP_INTERNET_GATEWAY";
	var NEXT_HOP_IP = "NEXT_HOP_IP";
	var NEXT_HOP_NETWORK = "NEXT_HOP_NETWORK";
	var NEXT_HOP_PEERING = "NEXT_HOP_PEERING";
	var NEXT_HOP_TYPE_UNSPECIFIED = "NEXT_HOP_TYPE_UNSPECIFIED";
	var NEXT_HOP_VPN_GATEWAY = "NEXT_HOP_VPN_GATEWAY";
	var NEXT_HOP_VPN_TUNNEL = "NEXT_HOP_VPN_TUNNEL";
}