package grest.compute.v1.types;
typedef FirewallPolicy = {
	/**
		A list of associations that belong to this firewall policy.
	**/
	@:optional
	var associations : Array<FirewallPolicyAssociation>;
	/**
		[Output Only] Creation timestamp in RFC3339 text format.
	**/
	@:optional
	var creationTimestamp : String;
	/**
		An optional description of this resource. Provide this property when you create the resource.
	**/
	@:optional
	var description : String;
	/**
		Depreacted, please use short name instead. User-provided name of the Organization firewall plicy. The name should be unique in the organization in which the firewall policy is created. The name must be 1-63 characters long, and comply with RFC1035. Specifically, the name must be 1-63 characters long and match the regular expression `[a-z]([-a-z0-9]*[a-z0-9])?` which means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or digit, except the last character, which cannot be a dash.
	**/
	@:optional
	var displayName : String;
	/**
		Specifies a fingerprint for this resource, which is essentially a hash of the metadata's contents and used for optimistic locking. The fingerprint is initially generated by Compute Engine and changes after every request to modify or update metadata. You must always provide an up-to-date fingerprint hash in order to update or change metadata, otherwise the request will fail with error 412 conditionNotMet.
		
		To see the latest fingerprint, make get() request to the firewall policy.
	**/
	@:optional
	var fingerprint : String;
	/**
		[Output Only] The unique identifier for the resource. This identifier is defined by the server.
	**/
	@:optional
	var id : String;
	/**
		[Output only] Type of the resource. Always compute#firewallPolicyfor firewall policies
	**/
	@:optional
	var kind : String;
	/**
		[Output Only] Name of the resource. It is a numeric ID allocated by GCP which uniquely identifies the Firewall Policy.
	**/
	@:optional
	var name : String;
	/**
		[Output Only] The parent of the firewall policy.
	**/
	@:optional
	var parent : String;
	/**
		[Output Only] Total count of all firewall policy rule tuples. A firewall policy can not exceed a set number of tuples.
	**/
	@:optional
	var ruleTupleCount : Int;
	/**
		A list of rules that belong to this policy. There must always be a default rule (rule with priority 2147483647 and match "*"). If no rules are provided when creating a firewall policy, a default rule with action "allow" will be added.
	**/
	@:optional
	var rules : Array<FirewallPolicyRule>;
	/**
		[Output Only] Server-defined URL for the resource.
	**/
	@:optional
	var selfLink : String;
	/**
		[Output Only] Server-defined URL for this resource with the resource id.
	**/
	@:optional
	var selfLinkWithId : String;
	/**
		User-provided name of the Organization firewall plicy. The name should be unique in the organization in which the firewall policy is created. The name must be 1-63 characters long, and comply with RFC1035. Specifically, the name must be 1-63 characters long and match the regular expression `[a-z]([-a-z0-9]*[a-z0-9])?` which means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or digit, except the last character, which cannot be a dash.
	**/
	@:optional
	var shortName : String;
}