package grest.compute.v1.types;
typedef InstanceGroup = {
	/**
		[Output Only] The creation timestamp for this instance group in RFC3339 text format.
	**/
	@:optional
	var creationTimestamp : String;
	/**
		An optional description of this resource. Provide this property when you create the resource.
	**/
	@:optional
	var description : String;
	/**
		[Output Only] The fingerprint of the named ports. The system uses this fingerprint to detect conflicts when multiple users change the named ports concurrently.
	**/
	@:optional
	var fingerprint : String;
	/**
		[Output Only] A unique identifier for this instance group, generated by the server.
	**/
	@:optional
	var id : String;
	/**
		[Output Only] The resource type, which is always compute#instanceGroup for instance groups.
	**/
	@:optional
	var kind : String;
	/**
		The name of the instance group. The name must be 1-63 characters long, and comply with RFC1035.
	**/
	@:optional
	var name : String;
	/**
		 Assigns a name to a port number. For example: {name: "http", port: 80} This allows the system to reference ports by the assigned name instead of a port number. Named ports can also contain multiple ports. For example: [{name: "http", port: 80},{name: "http", port: 8080}] Named ports apply to all instances in this instance group. 
	**/
	@:optional
	var namedPorts : Array<NamedPort>;
	/**
		[Output Only] The URL of the network to which all instances in the instance group belong. If your instance has multiple network interfaces, then the network and subnetwork fields only refer to the network and subnet used by your primary interface (nic0).
	**/
	@:optional
	var network : String;
	/**
		[Output Only] The URL of the region where the instance group is located (for regional resources).
	**/
	@:optional
	var region : String;
	/**
		[Output Only] The URL for this instance group. The server generates this URL.
	**/
	@:optional
	var selfLink : String;
	/**
		[Output Only] The total number of instances in the instance group.
	**/
	@:optional
	var size : Int;
	/**
		[Output Only] The URL of the subnetwork to which all instances in the instance group belong. If your instance has multiple network interfaces, then the network and subnetwork fields only refer to the network and subnet used by your primary interface (nic0).
	**/
	@:optional
	var subnetwork : String;
	/**
		[Output Only] The URL of the zone where the instance group is located (for zonal resources).
	**/
	@:optional
	var zone : String;
}