package grest.compute.v1.types;
typedef InterconnectOutageNotification = {
	/**
		If issue_type is IT_PARTIAL_OUTAGE, a list of the Google-side circuit IDs that will be affected.
	**/
	@:optional
	var affectedCircuits : Array<String>;
	/**
		A description about the purpose of the outage.
	**/
	@:optional
	var description : String;
	/**
		Scheduled end time for the outage (milliseconds since Unix epoch).
	**/
	@:optional
	var endTime : String;
	/**
		Form this outage is expected to take, which can take one of the following values: 
		- OUTAGE: The Interconnect may be completely out of service for some or all of the specified window. 
		- PARTIAL_OUTAGE: Some circuits comprising the Interconnect as a whole should remain up, but with reduced bandwidth. Note that the versions of this enum prefixed with "IT_" have been deprecated in favor of the unprefixed values.
	**/
	@:optional
	var issueType : grest.compute.v1.types.InterconnectOutageNotification_issueType;
	/**
		Unique identifier for this outage notification.
	**/
	@:optional
	var name : String;
	/**
		The party that generated this notification, which can take the following value: 
		- GOOGLE: this notification as generated by Google. Note that the value of NSRC_GOOGLE has been deprecated in favor of GOOGLE.
	**/
	@:optional
	var source : grest.compute.v1.types.InterconnectOutageNotification_source;
	/**
		Scheduled start time for the outage (milliseconds since Unix epoch).
	**/
	@:optional
	var startTime : String;
	/**
		State of this notification, which can take one of the following values: 
		- ACTIVE: This outage notification is active. The event could be in the past, present, or future. See start_time and end_time for scheduling. 
		- CANCELLED: The outage associated with this notification was cancelled before the outage was due to start. 
		- COMPLETED: The outage associated with this notification is complete.  Note that the versions of this enum prefixed with "NS_" have been deprecated in favor of the unprefixed values.
	**/
	@:optional
	var state : grest.compute.v1.types.InterconnectOutageNotification_state;
}