package grest.compute.v1.types;
@:enum abstract PublicAdvertisedPrefix_status(String) from String to String to tink.Stringly {
	var INITIAL = "INITIAL";
	var PREFIX_CONFIGURATION_COMPLETE = "PREFIX_CONFIGURATION_COMPLETE";
	var PREFIX_CONFIGURATION_IN_PROGRESS = "PREFIX_CONFIGURATION_IN_PROGRESS";
	var PREFIX_REMOVAL_IN_PROGRESS = "PREFIX_REMOVAL_IN_PROGRESS";
	var PTR_CONFIGURED = "PTR_CONFIGURED";
	var REVERSE_DNS_LOOKUP_FAILED = "REVERSE_DNS_LOOKUP_FAILED";
	var VALIDATED = "VALIDATED";
}