package grest.compute.v1.types;
@:enum abstract VpnTunnel_status(String) from String to String to tink.Stringly {
	var ALLOCATING_RESOURCES = "ALLOCATING_RESOURCES";
	var AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR";
	var DEPROVISIONING = "DEPROVISIONING";
	var ESTABLISHED = "ESTABLISHED";
	var FAILED = "FAILED";
	var FIRST_HANDSHAKE = "FIRST_HANDSHAKE";
	var NEGOTIATION_FAILURE = "NEGOTIATION_FAILURE";
	var NETWORK_ERROR = "NETWORK_ERROR";
	var NO_INCOMING_PACKETS = "NO_INCOMING_PACKETS";
	var PROVISIONING = "PROVISIONING";
	var REJECTED = "REJECTED";
	var STOPPED = "STOPPED";
	var WAITING_FOR_FULL_CONFIG = "WAITING_FOR_FULL_CONFIG";
}