package grest.gmailpostmastertools.v1.types;
@:enum abstract DeliveryError_errorType(String) from String to String to tink.Stringly {
	var BAD_ATTACHMENT = "BAD_ATTACHMENT";
	var BAD_DMARC_POLICY = "BAD_DMARC_POLICY";
	var BAD_PTR_RECORD = "BAD_PTR_RECORD";
	var CONTENT_SPAMMY = "CONTENT_SPAMMY";
	var DELIVERY_ERROR_TYPE_UNSPECIFIED = "DELIVERY_ERROR_TYPE_UNSPECIFIED";
	var DOMAIN_IN_RBL = "DOMAIN_IN_RBL";
	var IP_IN_RBL = "IP_IN_RBL";
	var LOW_DOMAIN_REPUTATION = "LOW_DOMAIN_REPUTATION";
	var LOW_IP_REPUTATION = "LOW_IP_REPUTATION";
	var RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED";
	var SUSPECTED_SPAM = "SUSPECTED_SPAM";
}