package grest.iam.v1.api;
interface IamPolicies {
	/**
		Lints, or validates, an IAM policy. Currently checks the google.iam.v1.Binding.condition field, which contains a condition expression for a role binding. Successful calls to this method always return an HTTP `200 OK` status code, even if the linter detects an issue in the IAM policy.
	**/
	@:post("/v1/iamPolicies:lintPolicy")
	function lintPolicy(body:grest.iam.v1.types.LintPolicyRequest):grest.iam.v1.types.LintPolicyResponse;
	/**
		Returns a list of services that allow you to opt into audit logs that are not generated by default. To learn more about audit logs, see the [Logging documentation](https://cloud.google.com/logging/docs/audit).
	**/
	@:post("/v1/iamPolicies:queryAuditableServices")
	function queryAuditableServices(body:grest.iam.v1.types.QueryAuditableServicesRequest):grest.iam.v1.types.QueryAuditableServicesResponse;
}