package grest.datafusion.v1.types;
typedef Instance = {
	/**
		List of accelerators enabled for this CDF instance.
	**/
	@:optional
	var accelerators : Array<Accelerator>;
	/**
		Output only. Endpoint on which the REST APIs is accessible.
	**/
	@:optional
	var apiEndpoint : String;
	/**
		Available versions that the instance can be upgraded to using UpdateInstanceRequest.
	**/
	@:optional
	var availableVersion : Array<Version>;
	/**
		Output only. The time the instance was created.
	**/
	@:optional
	var createTime : String;
	/**
		User-managed service account to set on Dataproc when Cloud Data Fusion creates Dataproc to run data processing pipelines. This allows users to have fine-grained access control on Dataproc's accesses to cloud resources.
	**/
	@:optional
	var dataprocServiceAccount : String;
	/**
		A description of this instance.
	**/
	@:optional
	var description : String;
	/**
		Display name for an instance.
	**/
	@:optional
	var displayName : String;
	/**
		Option to enable granular role-based access control.
	**/
	@:optional
	var enableRbac : Bool;
	/**
		Option to enable Stackdriver Logging.
	**/
	@:optional
	var enableStackdriverLogging : Bool;
	/**
		Option to enable Stackdriver Monitoring.
	**/
	@:optional
	var enableStackdriverMonitoring : Bool;
	/**
		Output only. Cloud Storage bucket generated by Data Fusion in the customer project.
	**/
	@:optional
	var gcsBucket : String;
	/**
		The resource labels for instance to use to annotate any related underlying resources such as GCE VMs. The character '=' is not allowed to be used within the labels.
	**/
	@:optional
	var labels : haxe.DynamicAccess<String>;
	/**
		Output only. The name of this instance is in the form of projects/{project}/locations/{location}/instances/{instance}.
	**/
	@:optional
	var name : String;
	/**
		Network configuration options. These are required when a private Data Fusion instance is to be created.
	**/
	@:optional
	var networkConfig : NetworkConfig;
	/**
		Map of additional options used to configure the behavior of Data Fusion instance.
	**/
	@:optional
	var options : haxe.DynamicAccess<String>;
	/**
		Output only. P4 service account for the customer project.
	**/
	@:optional
	var p4ServiceAccount : String;
	/**
		Specifies whether the Data Fusion instance should be private. If set to true, all Data Fusion nodes will have private IP addresses and will not be able to access the public internet.
	**/
	@:optional
	var privateInstance : Bool;
	/**
		Output only. Deprecated. Use tenant_project_id instead to extract the tenant project ID.
	**/
	@:optional
	var serviceAccount : String;
	/**
		Output only. Endpoint on which the Data Fusion UI is accessible.
	**/
	@:optional
	var serviceEndpoint : String;
	/**
		Output only. The current state of this Data Fusion instance.
	**/
	@:optional
	var state : grest.datafusion.v1.types.Instance_state;
	/**
		Output only. Additional information about the current state of this Data Fusion instance if available.
	**/
	@:optional
	var stateMessage : String;
	/**
		Output only. The name of the tenant project.
	**/
	@:optional
	var tenantProjectId : String;
	/**
		Required. Instance type.
	**/
	@:optional
	var type : grest.datafusion.v1.types.Instance_type;
	/**
		Output only. The time the instance was last updated.
	**/
	@:optional
	var updateTime : String;
	/**
		Current version of the Data Fusion. Only specifiable in Update.
	**/
	@:optional
	var version : String;
	/**
		Name of the zone in which the Data Fusion instance will be created. Only DEVELOPER instances use this field.
	**/
	@:optional
	var zone : String;
}