package grest.cloudresourcemanager.v3.types;
@:enum abstract FolderOperationError_errorMessageId(String) from String to String to tink.Stringly {
	var ACTIVE_FOLDER_HEIGHT_VIOLATION = "ACTIVE_FOLDER_HEIGHT_VIOLATION";
	var CYCLE_INTRODUCED_VIOLATION = "CYCLE_INTRODUCED_VIOLATION";
	var DELETED_FOLDER_HEIGHT_VIOLATION = "DELETED_FOLDER_HEIGHT_VIOLATION";
	var ERROR_TYPE_UNSPECIFIED = "ERROR_TYPE_UNSPECIFIED";
	var FOLDER_BEING_MOVED_VIOLATION = "FOLDER_BEING_MOVED_VIOLATION";
	var FOLDER_NAME_UNIQUENESS_VIOLATION = "FOLDER_NAME_UNIQUENESS_VIOLATION";
	var FOLDER_TO_DELETE_NON_EMPTY_VIOLATION = "FOLDER_TO_DELETE_NON_EMPTY_VIOLATION";
	var MAX_CHILD_FOLDERS_VIOLATION = "MAX_CHILD_FOLDERS_VIOLATION";
	var PARENT_DELETED_VIOLATION = "PARENT_DELETED_VIOLATION";
	var RESOURCE_DELETED_VIOLATION = "RESOURCE_DELETED_VIOLATION";
}