package grest.testing.v1.types;
@:enum abstract TestExecution_state(String) from String to String to tink.Stringly {
	var CANCELLED = "CANCELLED";
	var ERROR = "ERROR";
	var FINISHED = "FINISHED";
	var INCOMPATIBLE_ARCHITECTURE = "INCOMPATIBLE_ARCHITECTURE";
	var INCOMPATIBLE_ENVIRONMENT = "INCOMPATIBLE_ENVIRONMENT";
	var INVALID = "INVALID";
	var PENDING = "PENDING";
	var RUNNING = "RUNNING";
	var TEST_STATE_UNSPECIFIED = "TEST_STATE_UNSPECIFIED";
	var UNSUPPORTED_ENVIRONMENT = "UNSUPPORTED_ENVIRONMENT";
	var VALIDATING = "VALIDATING";
}