package grest.androidmanagement.v1.types;
@:enum abstract ApplicationPolicy_connectedWorkAndPersonalApp(String) from String to String to tink.Stringly {
	var CONNECTED_WORK_AND_PERSONAL_APP_ALLOWED = "CONNECTED_WORK_AND_PERSONAL_APP_ALLOWED";
	var CONNECTED_WORK_AND_PERSONAL_APP_DISALLOWED = "CONNECTED_WORK_AND_PERSONAL_APP_DISALLOWED";
	var CONNECTED_WORK_AND_PERSONAL_APP_UNSPECIFIED = "CONNECTED_WORK_AND_PERSONAL_APP_UNSPECIFIED";
}