package grest.androidmanagement.v1.types;
typedef Command = {
	/**
		The timestamp at which the command was created. The timestamp is automatically generated by the server.
	**/
	@:optional
	var createTime : String;
	/**
		The duration for which the command is valid. The command will expire if not executed by the device during this time. The default duration if unspecified is ten minutes. There is no maximum duration.
	**/
	@:optional
	var duration : String;
	/**
		If the command failed, an error code explaining the failure. This is not set when the command is cancelled by the caller.
	**/
	@:optional
	var errorCode : grest.androidmanagement.v1.types.Command_errorCode;
	/**
		For commands of type RESET_PASSWORD, optionally specifies the new password.
	**/
	@:optional
	var newPassword : String;
	/**
		For commands of type RESET_PASSWORD, optionally specifies flags.
	**/
	@:optional
	var resetPasswordFlags : Array<String>;
	/**
		The type of the command.
	**/
	@:optional
	var type : grest.androidmanagement.v1.types.Command_type;
	/**
		The resource name of the user that owns the device in the form enterprises/{enterpriseId}/users/{userId}. This is automatically generated by the server based on the device the command is sent to.
	**/
	@:optional
	var userName : String;
}