package grest.androidmanagement.v1.types;
typedef EnrollmentToken = {
	/**
		Optional, arbitrary data associated with the enrollment token. This could contain, for example, the ID of an org unit the device is assigned to after enrollment. After a device enrolls with the token, this data will be exposed in the enrollment_token_data field of the Device resource. The data must be 1024 characters or less; otherwise, the creation request will fail.
	**/
	@:optional
	var additionalData : String;
	/**
		Controls whether personal usage is allowed on a device provisioned with this enrollment token.For company-owned devices: Enabling personal usage allows the user to set up a work profile on the device. Disabling personal usage requires the user provision the device as a fully managed device.For personally-owned devices: Enabling personal usage allows the user to set up a work profile on the device. Disabling personal usage will prevent the device from provisioning. Personal usage cannot be disabled on personally-owned device.
	**/
	@:optional
	var allowPersonalUsage : grest.androidmanagement.v1.types.EnrollmentToken_allowPersonalUsage;
	/**
		The length of time the enrollment token is valid, ranging from 1 minute to 90 days. If not specified, the default duration is 1 hour.
	**/
	@:optional
	var duration : String;
	/**
		The expiration time of the token. This is a read-only field generated by the server.
	**/
	@:optional
	var expirationTimestamp : String;
	/**
		The name of the enrollment token, which is generated by the server during creation, in the form enterprises/{enterpriseId}/enrollmentTokens/{enrollmentTokenId}.
	**/
	@:optional
	var name : String;
	/**
		Whether the enrollment token is for one time use only. If the flag is set to true, only one device can use it for registration.
	**/
	@:optional
	var oneTimeOnly : Bool;
	/**
		The name of the policy initially applied to the enrolled device, in the form enterprises/{enterpriseId}/policies/{policyId}. If not specified, the policy_name for the device’s user is applied. If user_name is also not specified, enterprises/{enterpriseId}/policies/default is applied by default. When updating this field, you can specify only the policyId as long as the policyId doesn’t contain any slashes. The rest of the policy name will be inferred.
	**/
	@:optional
	var policyName : String;
	/**
		A JSON string whose UTF-8 representation can be used to generate a QR code to enroll a device with this enrollment token. To enroll a device using NFC, the NFC record must contain a serialized java.util.Properties representation of the properties in the JSON.
	**/
	@:optional
	var qrCode : String;
	/**
		The user associated with this enrollment token. If it's specified when the enrollment token is created and the user does not exist, the user will be created. This field must not contain personally identifiable information. Only the account_identifier field needs to be set.
	**/
	@:optional
	var user : User;
	/**
		The token value that's passed to the device and authorizes the device to enroll. This is a read-only field generated by the server.
	**/
	@:optional
	var value : String;
}