package grest.androidmanagement.v1.types;
typedef Enterprise = {
	/**
		Deprecated and unused.
	**/
	@:optional
	var appAutoApprovalEnabled : Bool;
	/**
		This feature is not generally available yet. The enterprise contact info of an EMM owned enterprise
	**/
	@:optional
	var contactInfo : ContactInfo;
	/**
		The types of Google Pub/Sub notifications enabled for the enterprise.
	**/
	@:optional
	var enabledNotificationTypes : Array<String>;
	/**
		The name of the enterprise displayed to users.
	**/
	@:optional
	var enterpriseDisplayName : String;
	/**
		An image displayed as a logo during device provisioning. Supported types are: image/bmp, image/gif, image/x-ico, image/jpeg, image/png, image/webp, image/vnd.wap.wbmp, image/x-adobe-dng.
	**/
	@:optional
	var logo : ExternalData;
	/**
		The name of the enterprise which is generated by the server during creation, in the form enterprises/{enterpriseId}.
	**/
	@:optional
	var name : String;
	/**
		A color in RGB format that indicates the predominant color to display in the device management app UI. The color components are stored as follows: (red << 16) | (green << 8) | blue, where the value of each component is between 0 and 255, inclusive.
	**/
	@:optional
	var primaryColor : Int;
	/**
		The topic that Cloud Pub/Sub notifications are published to, in the form projects/{project}/topics/{topic}. This field is only required if Pub/Sub notifications are enabled.
	**/
	@:optional
	var pubsubTopic : String;
	/**
		Sign-in details of the enterprise.
	**/
	@:optional
	var signinDetails : Array<SigninDetail>;
	/**
		Terms and conditions that must be accepted when provisioning a device for this enterprise. A page of terms is generated for each value in this list.
	**/
	@:optional
	var termsAndConditions : Array<TermsAndConditions>;
}