package grest.androidmanagement.v1.types;
@:enum abstract NonComplianceDetail_installationFailureReason(String) from String to String to tink.Stringly {
	var INSTALLATION_FAILURE_REASON_UNKNOWN = "INSTALLATION_FAILURE_REASON_UNKNOWN";
	var INSTALLATION_FAILURE_REASON_UNSPECIFIED = "INSTALLATION_FAILURE_REASON_UNSPECIFIED";
	var IN_PROGRESS = "IN_PROGRESS";
	var NOT_APPROVED = "NOT_APPROVED";
	var NOT_AVAILABLE_IN_COUNTRY = "NOT_AVAILABLE_IN_COUNTRY";
	var NOT_COMPATIBLE_WITH_DEVICE = "NOT_COMPATIBLE_WITH_DEVICE";
	var NOT_ENROLLED = "NOT_ENROLLED";
	var NOT_FOUND = "NOT_FOUND";
	var NO_LICENSES_REMAINING = "NO_LICENSES_REMAINING";
	var PERMISSIONS_NOT_ACCEPTED = "PERMISSIONS_NOT_ACCEPTED";
	var USER_INVALID = "USER_INVALID";
}