package grest.androidmanagement.v1.types;
typedef SigninDetail = {
	/**
		Controls whether personal usage is allowed on a device provisioned with this enrollment token.For company-owned devices: Enabling personal usage allows the user to set up a work profile on the device. Disabling personal usage requires the user provision the device as a fully managed device.For personally-owned devices: Enabling personal usage allows the user to set up a work profile on the device. Disabling personal usage will prevent the device from provisioning. Personal usage cannot be disabled on personally-owned device.
	**/
	@:optional
	var allowPersonalUsage : grest.androidmanagement.v1.types.SigninDetail_allowPersonalUsage;
	/**
		A JSON string whose UTF-8 representation can be used to generate a QR code to enroll a device with this enrollment token. To enroll a device using NFC, the NFC record must contain a serialized java.util.Properties representation of the properties in the JSON. This is a read-only field generated by the server.
	**/
	@:optional
	var qrCode : String;
	/**
		An enterprise wide enrollment token used to trigger custom sign-in flow. This is a read-only field generated by the server.
	**/
	@:optional
	var signinEnrollmentToken : String;
	/**
		Sign-in URL for authentication when device is provisioned with a sign-in enrollment token. The sign-in endpoint should finish authentication flow with a URL in the form of https://enterprise.google.com/android/enroll?et= for a successful login, or https://enterprise.google.com/android/enroll/invalid for a failed login.
	**/
	@:optional
	var signinUrl : String;
}