package grest.androidmanagement.v1.types;
typedef WebApp = {
	/**
		The display mode of the web app.
	**/
	@:optional
	var displayMode : grest.androidmanagement.v1.types.WebApp_displayMode;
	/**
		A list of icons for the web app. Must have at least one element.
	**/
	@:optional
	var icons : Array<WebAppIcon>;
	/**
		The name of the web app, which is generated by the server during creation in the form enterprises/{enterpriseId}/webApps/{packageName}.
	**/
	@:optional
	var name : String;
	/**
		The start URL, i.e. the URL that should load when the user opens the application.
	**/
	@:optional
	var startUrl : String;
	/**
		The title of the web app as displayed to the user (e.g., amongst a list of other applications, or as a label for an icon).
	**/
	@:optional
	var title : String;
	/**
		The current version of the app.Note that the version can automatically increase during the lifetime of the web app, while Google does internal housekeeping to keep the web app up-to-date.
	**/
	@:optional
	var versionCode : String;
}