package grest.androidmanagement.v1.types;
typedef WebToken = {
	/**
		The features to enable. Use this if you want to control exactly which feature(s) will be activated; leave empty to allow all features.Restrictions / things to note: - If no features are listed here, all features are enabled — this is the default behavior where you give access to all features to your admins. - This must not contain any FEATURE_UNSPECIFIED values. - Repeated values are ignored 
	**/
	@:optional
	var enabledFeatures : Array<String>;
	/**
		The name of the web token, which is generated by the server during creation in the form enterprises/{enterpriseId}/webTokens/{webTokenId}.
	**/
	@:optional
	var name : String;
	/**
		The URL of the parent frame hosting the iframe with the embedded UI. To prevent XSS, the iframe may not be hosted at other URLs. The URL must use the https scheme.
	**/
	@:optional
	var parentFrameUrl : String;
	/**
		Permissions available to an admin in the embedded UI. An admin must have all of these permissions in order to view the UI. This field is deprecated.
	**/
	@:optional
	var permissions : Array<String>;
	/**
		The token value which is used in the hosting page to generate the iframe with the embedded UI. This is a read-only field generated by the server.
	**/
	@:optional
	var value : String;
}