package grest.osconfig.v1.types;
@:enum abstract PatchJobInstanceDetails_state(String) from String to String to tink.Stringly {
	var ACKED = "ACKED";
	var APPLYING_PATCHES = "APPLYING_PATCHES";
	var DOWNLOADING_PATCHES = "DOWNLOADING_PATCHES";
	var FAILED = "FAILED";
	var INACTIVE = "INACTIVE";
	var NOTIFIED = "NOTIFIED";
	var NO_AGENT_DETECTED = "NO_AGENT_DETECTED";
	var PATCH_STATE_UNSPECIFIED = "PATCH_STATE_UNSPECIFIED";
	var PENDING = "PENDING";
	var REBOOTING = "REBOOTING";
	var RUNNING_POST_PATCH_STEP = "RUNNING_POST_PATCH_STEP";
	var RUNNING_PRE_PATCH_STEP = "RUNNING_PRE_PATCH_STEP";
	var STARTED = "STARTED";
	var SUCCEEDED = "SUCCEEDED";
	var SUCCEEDED_REBOOT_REQUIRED = "SUCCEEDED_REBOOT_REQUIRED";
	var TIMED_OUT = "TIMED_OUT";
}