package grest.dialogflow.v3.types;
typedef GoogleCloudDialogflowCxV3Version = {
	/**
		Output only. Create time of the version.
	**/
	@:optional
	var createTime : String;
	/**
		The description of the version. The maximum length is 500 characters. If exceeded, the request is rejected.
	**/
	@:optional
	var description : String;
	/**
		Required. The human-readable name of the version. Limit of 64 characters.
	**/
	@:optional
	var displayName : String;
	/**
		Format: projects//locations//agents//flows//versions/. Version ID is a self-increasing number generated by Dialogflow upon version creation.
	**/
	@:optional
	var name : String;
	/**
		Output only. The NLU settings of the flow at version creation.
	**/
	@:optional
	var nluSettings : GoogleCloudDialogflowCxV3NluSettings;
	/**
		Output only. The state of this version. This field is read-only and cannot be set by create and update methods.
	**/
	@:optional
	var state : grest.dialogflow.v3.types.GoogleCloudDialogflowCxV3Version_state;
}