package grest.dialogflow.v3.types;
@:enum abstract GoogleCloudDialogflowCxV3InputAudioConfig_audioEncoding(String) from String to String to tink.Stringly {
	var AUDIO_ENCODING_AMR = "AUDIO_ENCODING_AMR";
	var AUDIO_ENCODING_AMR_WB = "AUDIO_ENCODING_AMR_WB";
	var AUDIO_ENCODING_FLAC = "AUDIO_ENCODING_FLAC";
	var AUDIO_ENCODING_LINEAR_16 = "AUDIO_ENCODING_LINEAR_16";
	var AUDIO_ENCODING_MULAW = "AUDIO_ENCODING_MULAW";
	var AUDIO_ENCODING_OGG_OPUS = "AUDIO_ENCODING_OGG_OPUS";
	var AUDIO_ENCODING_SPEEX_WITH_HEADER_BYTE = "AUDIO_ENCODING_SPEEX_WITH_HEADER_BYTE";
	var AUDIO_ENCODING_UNSPECIFIED = "AUDIO_ENCODING_UNSPECIFIED";
}