package grest.dialogflow.v3.types;
typedef GoogleCloudDialogflowCxV3beta1ResponseMessage = {
	/**
		Indicates that the conversation succeeded.
	**/
	@:optional
	var conversationSuccess : GoogleCloudDialogflowCxV3beta1ResponseMessageConversationSuccess;
	/**
		Output only. A signal that indicates the interaction with the Dialogflow agent has ended. This message is generated by Dialogflow only when the conversation reaches `END_SESSION` page. It is not supposed to be defined by the user. It's guaranteed that there is at most one such message in each response.
	**/
	@:optional
	var endInteraction : GoogleCloudDialogflowCxV3beta1ResponseMessageEndInteraction;
	/**
		Hands off conversation to a human agent.
	**/
	@:optional
	var liveAgentHandoff : GoogleCloudDialogflowCxV3beta1ResponseMessageLiveAgentHandoff;
	/**
		Output only. An audio response message composed of both the synthesized Dialogflow agent responses and responses defined via play_audio. This message is generated by Dialogflow only and not supposed to be defined by the user.
	**/
	@:optional
	var mixedAudio : GoogleCloudDialogflowCxV3beta1ResponseMessageMixedAudio;
	/**
		A text or ssml response that is preferentially used for TTS output audio synthesis, as described in the comment on the ResponseMessage message.
	**/
	@:optional
	var outputAudioText : GoogleCloudDialogflowCxV3beta1ResponseMessageOutputAudioText;
	/**
		Returns a response containing a custom, platform-specific payload.
	**/
	@:optional
	var payload : haxe.DynamicAccess<tink.json.Value>;
	/**
		Signal that the client should play an audio clip hosted at a client-specific URI. Dialogflow uses this to construct mixed_audio. However, Dialogflow itself does not try to read or process the URI in any way.
	**/
	@:optional
	var playAudio : GoogleCloudDialogflowCxV3beta1ResponseMessagePlayAudio;
	/**
		Returns a text response.
	**/
	@:optional
	var text : GoogleCloudDialogflowCxV3beta1ResponseMessageText;
}