package grest.dataproc.v1.types;
typedef JobPlacement = {
	/**
		Optional. Cluster labels to identify a cluster where the job will be submitted.
	**/
	@:optional
	var clusterLabels : haxe.DynamicAccess<String>;
	/**
		Required. The name of the cluster where the job will be submitted.
	**/
	@:optional
	var clusterName : String;
	/**
		Output only. A cluster UUID generated by the Dataproc service when the job is submitted.
	**/
	@:optional
	var clusterUuid : String;
}