package grest.dataproc.v1.types;
typedef KerberosConfig = {
	/**
		Optional. The admin server (IP or hostname) for the remote trusted realm in a cross realm trust relationship.
	**/
	@:optional
	var crossRealmTrustAdminServer : String;
	/**
		Optional. The KDC (IP or hostname) for the remote trusted realm in a cross realm trust relationship.
	**/
	@:optional
	var crossRealmTrustKdc : String;
	/**
		Optional. The remote realm the Dataproc on-cluster KDC will trust, should the user enable cross realm trust.
	**/
	@:optional
	var crossRealmTrustRealm : String;
	/**
		Optional. The Cloud Storage URI of a KMS encrypted file containing the shared password between the on-cluster Kerberos realm and the remote trusted realm, in a cross realm trust relationship.
	**/
	@:optional
	var crossRealmTrustSharedPasswordUri : String;
	/**
		Optional. Flag to indicate whether to Kerberize the cluster (default: false). Set this field to true to enable Kerberos on a cluster.
	**/
	@:optional
	var enableKerberos : Bool;
	/**
		Optional. The Cloud Storage URI of a KMS encrypted file containing the master key of the KDC database.
	**/
	@:optional
	var kdcDbKeyUri : String;
	/**
		Optional. The Cloud Storage URI of a KMS encrypted file containing the password to the user provided key. For the self-signed certificate, this password is generated by Dataproc.
	**/
	@:optional
	var keyPasswordUri : String;
	/**
		Optional. The Cloud Storage URI of a KMS encrypted file containing the password to the user provided keystore. For the self-signed certificate, this password is generated by Dataproc.
	**/
	@:optional
	var keystorePasswordUri : String;
	/**
		Optional. The Cloud Storage URI of the keystore file used for SSL encryption. If not provided, Dataproc will provide a self-signed certificate.
	**/
	@:optional
	var keystoreUri : String;
	/**
		Optional. The uri of the KMS key used to encrypt various sensitive files.
	**/
	@:optional
	var kmsKeyUri : String;
	/**
		Optional. The name of the on-cluster Kerberos realm. If not specified, the uppercased domain of hostnames will be the realm.
	**/
	@:optional
	var realm : String;
	/**
		Optional. The Cloud Storage URI of a KMS encrypted file containing the root principal password.
	**/
	@:optional
	var rootPrincipalPasswordUri : String;
	/**
		Optional. The lifetime of the ticket granting ticket, in hours. If not specified, or user specifies 0, then default value 10 will be used.
	**/
	@:optional
	var tgtLifetimeHours : Int;
	/**
		Optional. The Cloud Storage URI of a KMS encrypted file containing the password to the user provided truststore. For the self-signed certificate, this password is generated by Dataproc.
	**/
	@:optional
	var truststorePasswordUri : String;
	/**
		Optional. The Cloud Storage URI of the truststore file used for SSL encryption. If not provided, Dataproc will provide a self-signed certificate.
	**/
	@:optional
	var truststoreUri : String;
}