package grest.appengine.v1.types;
@:enum abstract NetworkSettings_ingressTrafficAllowed(String) from String to String to tink.Stringly {
	var INGRESS_TRAFFIC_ALLOWED_ALL = "INGRESS_TRAFFIC_ALLOWED_ALL";
	var INGRESS_TRAFFIC_ALLOWED_INTERNAL_AND_LB = "INGRESS_TRAFFIC_ALLOWED_INTERNAL_AND_LB";
	var INGRESS_TRAFFIC_ALLOWED_INTERNAL_ONLY = "INGRESS_TRAFFIC_ALLOWED_INTERNAL_ONLY";
	var INGRESS_TRAFFIC_ALLOWED_UNSPECIFIED = "INGRESS_TRAFFIC_ALLOWED_UNSPECIFIED";
}