package grest.appengine.v1.types;
@:enum abstract UrlMap_redirectHttpResponseCode(String) from String to String to tink.Stringly {
	var REDIRECT_HTTP_RESPONSE_CODE_301 = "REDIRECT_HTTP_RESPONSE_CODE_301";
	var REDIRECT_HTTP_RESPONSE_CODE_302 = "REDIRECT_HTTP_RESPONSE_CODE_302";
	var REDIRECT_HTTP_RESPONSE_CODE_303 = "REDIRECT_HTTP_RESPONSE_CODE_303";
	var REDIRECT_HTTP_RESPONSE_CODE_307 = "REDIRECT_HTTP_RESPONSE_CODE_307";
	var REDIRECT_HTTP_RESPONSE_CODE_UNSPECIFIED = "REDIRECT_HTTP_RESPONSE_CODE_UNSPECIFIED";
}