package grest.bigquery.v2.types;
@:enum abstract Model_modelType(String) from String to String to tink.Stringly {
	var ARIMA = "ARIMA";
	var ARIMA_PLUS = "ARIMA_PLUS";
	var AUTOML_CLASSIFIER = "AUTOML_CLASSIFIER";
	var AUTOML_REGRESSOR = "AUTOML_REGRESSOR";
	var BOOSTED_TREE_CLASSIFIER = "BOOSTED_TREE_CLASSIFIER";
	var BOOSTED_TREE_REGRESSOR = "BOOSTED_TREE_REGRESSOR";
	var DNN_CLASSIFIER = "DNN_CLASSIFIER";
	var DNN_REGRESSOR = "DNN_REGRESSOR";
	var KMEANS = "KMEANS";
	var LINEAR_REGRESSION = "LINEAR_REGRESSION";
	var LOGISTIC_REGRESSION = "LOGISTIC_REGRESSION";
	var MATRIX_FACTORIZATION = "MATRIX_FACTORIZATION";
	var MODEL_TYPE_UNSPECIFIED = "MODEL_TYPE_UNSPECIFIED";
	var TENSORFLOW = "TENSORFLOW";
}