package grest.vision.v1.types;
@:enum abstract Feature_type(String) from String to String to tink.Stringly {
	var CROP_HINTS = "CROP_HINTS";
	var DOCUMENT_TEXT_DETECTION = "DOCUMENT_TEXT_DETECTION";
	var FACE_DETECTION = "FACE_DETECTION";
	var IMAGE_PROPERTIES = "IMAGE_PROPERTIES";
	var LABEL_DETECTION = "LABEL_DETECTION";
	var LANDMARK_DETECTION = "LANDMARK_DETECTION";
	var LOGO_DETECTION = "LOGO_DETECTION";
	var OBJECT_LOCALIZATION = "OBJECT_LOCALIZATION";
	var PRODUCT_SEARCH = "PRODUCT_SEARCH";
	var SAFE_SEARCH_DETECTION = "SAFE_SEARCH_DETECTION";
	var TEXT_DETECTION = "TEXT_DETECTION";
	var TYPE_UNSPECIFIED = "TYPE_UNSPECIFIED";
	var WEB_DETECTION = "WEB_DETECTION";
}