package grest.displayvideo.v1.types;
@:enum abstract ActiveViewVideoViewabilityMetricConfig_minimumQuartile(String) from String to String to tink.Stringly {
	var VIDEO_DURATION_QUARTILE_FIRST = "VIDEO_DURATION_QUARTILE_FIRST";
	var VIDEO_DURATION_QUARTILE_FOURTH = "VIDEO_DURATION_QUARTILE_FOURTH";
	var VIDEO_DURATION_QUARTILE_NONE = "VIDEO_DURATION_QUARTILE_NONE";
	var VIDEO_DURATION_QUARTILE_SECOND = "VIDEO_DURATION_QUARTILE_SECOND";
	var VIDEO_DURATION_QUARTILE_THIRD = "VIDEO_DURATION_QUARTILE_THIRD";
	var VIDEO_DURATION_QUARTILE_UNSPECIFIED = "VIDEO_DURATION_QUARTILE_UNSPECIFIED";
}