package grest.displayvideo.v1.types;
@:enum abstract ActiveViewVideoViewabilityMetricConfig_minimumViewability(String) from String to String to tink.Stringly {
	var VIEWABILITY_PERCENT_0 = "VIEWABILITY_PERCENT_0";
	var VIEWABILITY_PERCENT_100 = "VIEWABILITY_PERCENT_100";
	var VIEWABILITY_PERCENT_25 = "VIEWABILITY_PERCENT_25";
	var VIEWABILITY_PERCENT_50 = "VIEWABILITY_PERCENT_50";
	var VIEWABILITY_PERCENT_75 = "VIEWABILITY_PERCENT_75";
	var VIEWABILITY_PERCENT_UNSPECIFIED = "VIEWABILITY_PERCENT_UNSPECIFIED";
}