package grest.displayvideo.v1.types;
@:enum abstract ActiveViewVideoViewabilityMetricConfig_minimumDuration(String) from String to String to tink.Stringly {
	var VIDEO_DURATION_SECONDS_0 = "VIDEO_DURATION_SECONDS_0";
	var VIDEO_DURATION_SECONDS_1 = "VIDEO_DURATION_SECONDS_1";
	var VIDEO_DURATION_SECONDS_10 = "VIDEO_DURATION_SECONDS_10";
	var VIDEO_DURATION_SECONDS_11 = "VIDEO_DURATION_SECONDS_11";
	var VIDEO_DURATION_SECONDS_12 = "VIDEO_DURATION_SECONDS_12";
	var VIDEO_DURATION_SECONDS_13 = "VIDEO_DURATION_SECONDS_13";
	var VIDEO_DURATION_SECONDS_14 = "VIDEO_DURATION_SECONDS_14";
	var VIDEO_DURATION_SECONDS_15 = "VIDEO_DURATION_SECONDS_15";
	var VIDEO_DURATION_SECONDS_2 = "VIDEO_DURATION_SECONDS_2";
	var VIDEO_DURATION_SECONDS_3 = "VIDEO_DURATION_SECONDS_3";
	var VIDEO_DURATION_SECONDS_30 = "VIDEO_DURATION_SECONDS_30";
	var VIDEO_DURATION_SECONDS_4 = "VIDEO_DURATION_SECONDS_4";
	var VIDEO_DURATION_SECONDS_45 = "VIDEO_DURATION_SECONDS_45";
	var VIDEO_DURATION_SECONDS_5 = "VIDEO_DURATION_SECONDS_5";
	var VIDEO_DURATION_SECONDS_6 = "VIDEO_DURATION_SECONDS_6";
	var VIDEO_DURATION_SECONDS_60 = "VIDEO_DURATION_SECONDS_60";
	var VIDEO_DURATION_SECONDS_7 = "VIDEO_DURATION_SECONDS_7";
	var VIDEO_DURATION_SECONDS_8 = "VIDEO_DURATION_SECONDS_8";
	var VIDEO_DURATION_SECONDS_9 = "VIDEO_DURATION_SECONDS_9";
	var VIDEO_DURATION_SECONDS_NONE = "VIDEO_DURATION_SECONDS_NONE";
	var VIDEO_DURATION_UNSPECIFIED = "VIDEO_DURATION_UNSPECIFIED";
}