package grest.displayvideo.v1.types;
@:enum abstract AppAssignedTargetingOptionDetails_appPlatform(String) from String to String to tink.Stringly {
	var APP_PLATFORM_AMAZON_FIRETV = "APP_PLATFORM_AMAZON_FIRETV";
	var APP_PLATFORM_ANDROID = "APP_PLATFORM_ANDROID";
	var APP_PLATFORM_ANDROID_TV = "APP_PLATFORM_ANDROID_TV";
	var APP_PLATFORM_APPLE_TV = "APP_PLATFORM_APPLE_TV";
	var APP_PLATFORM_GENERIC_CTV = "APP_PLATFORM_GENERIC_CTV";
	var APP_PLATFORM_IOS = "APP_PLATFORM_IOS";
	var APP_PLATFORM_PLAYSTATION = "APP_PLATFORM_PLAYSTATION";
	var APP_PLATFORM_ROKU = "APP_PLATFORM_ROKU";
	var APP_PLATFORM_SAMSUNG_TV = "APP_PLATFORM_SAMSUNG_TV";
	var APP_PLATFORM_UNSPECIFIED = "APP_PLATFORM_UNSPECIFIED";
	var APP_PLATFORM_XBOX = "APP_PLATFORM_XBOX";
}