package grest.displayvideo.v1.types;
@:enum abstract AssetAssociation_role(String) from String to String to tink.Stringly {
	var ASSET_ROLE_ADVERTISER_NAME = "ASSET_ROLE_ADVERTISER_NAME";
	var ASSET_ROLE_ANDROID_APP_ID = "ASSET_ROLE_ANDROID_APP_ID";
	var ASSET_ROLE_BACKUP = "ASSET_ROLE_BACKUP";
	var ASSET_ROLE_BODY = "ASSET_ROLE_BODY";
	var ASSET_ROLE_CALL_TO_ACTION = "ASSET_ROLE_CALL_TO_ACTION";
	var ASSET_ROLE_CAPTION_URL = "ASSET_ROLE_CAPTION_URL";
	var ASSET_ROLE_COVER_IMAGE = "ASSET_ROLE_COVER_IMAGE";
	var ASSET_ROLE_HEADLINE = "ASSET_ROLE_HEADLINE";
	var ASSET_ROLE_ICON = "ASSET_ROLE_ICON";
	var ASSET_ROLE_IOS_APP_ID = "ASSET_ROLE_IOS_APP_ID";
	var ASSET_ROLE_LONG_BODY = "ASSET_ROLE_LONG_BODY";
	var ASSET_ROLE_LONG_HEADLINE = "ASSET_ROLE_LONG_HEADLINE";
	var ASSET_ROLE_MAIN = "ASSET_ROLE_MAIN";
	var ASSET_ROLE_POLITE_LOAD = "ASSET_ROLE_POLITE_LOAD";
	var ASSET_ROLE_PRICE = "ASSET_ROLE_PRICE";
	var ASSET_ROLE_RATING = "ASSET_ROLE_RATING";
	var ASSET_ROLE_UNSPECIFIED = "ASSET_ROLE_UNSPECIFIED";
}