package grest.displayvideo.v1.types;
@:enum abstract AssignedUserRole_userRole(String) from String to String to tink.Stringly {
	var ADMIN = "ADMIN";
	var ADMIN_PARTNER_CLIENT = "ADMIN_PARTNER_CLIENT";
	var CREATIVE = "CREATIVE";
	var CREATIVE_ADMIN = "CREATIVE_ADMIN";
	var LIMITED_REPORTING_ONLY = "LIMITED_REPORTING_ONLY";
	var READ_ONLY = "READ_ONLY";
	var REPORTING_ONLY = "REPORTING_ONLY";
	var STANDARD = "STANDARD";
	var STANDARD_PARTNER_CLIENT = "STANDARD_PARTNER_CLIENT";
	var STANDARD_PLANNER = "STANDARD_PLANNER";
	var STANDARD_PLANNER_LIMITED = "STANDARD_PLANNER_LIMITED";
	var USER_ROLE_UNSPECIFIED = "USER_ROLE_UNSPECIFIED";
}