package grest.displayvideo.v1.types;
@:enum abstract CampaignGoal_campaignGoalType(String) from String to String to tink.Stringly {
	var CAMPAIGN_GOAL_TYPE_APP_INSTALL = "CAMPAIGN_GOAL_TYPE_APP_INSTALL";
	var CAMPAIGN_GOAL_TYPE_BRAND_AWARENESS = "CAMPAIGN_GOAL_TYPE_BRAND_AWARENESS";
	var CAMPAIGN_GOAL_TYPE_OFFLINE_ACTION = "CAMPAIGN_GOAL_TYPE_OFFLINE_ACTION";
	var CAMPAIGN_GOAL_TYPE_ONLINE_ACTION = "CAMPAIGN_GOAL_TYPE_ONLINE_ACTION";
	var CAMPAIGN_GOAL_TYPE_UNSPECIFIED = "CAMPAIGN_GOAL_TYPE_UNSPECIFIED";
}