package grest.displayvideo.v1.types;
@:enum abstract ContentInstreamPositionTargetingOptionDetails_contentInstreamPosition(String) from String to String to tink.Stringly {
	var CONTENT_INSTREAM_POSITION_MID_ROLL = "CONTENT_INSTREAM_POSITION_MID_ROLL";
	var CONTENT_INSTREAM_POSITION_POST_ROLL = "CONTENT_INSTREAM_POSITION_POST_ROLL";
	var CONTENT_INSTREAM_POSITION_PRE_ROLL = "CONTENT_INSTREAM_POSITION_PRE_ROLL";
	var CONTENT_INSTREAM_POSITION_UNKNOWN = "CONTENT_INSTREAM_POSITION_UNKNOWN";
	var CONTENT_INSTREAM_POSITION_UNSPECIFIED = "CONTENT_INSTREAM_POSITION_UNSPECIFIED";
}