package grest.displayvideo.v1.types;
@:enum abstract ContentOutstreamPositionTargetingOptionDetails_contentOutstreamPosition(String) from String to String to tink.Stringly {
	var CONTENT_OUTSTREAM_POSITION_INTERSTITIAL = "CONTENT_OUTSTREAM_POSITION_INTERSTITIAL";
	var CONTENT_OUTSTREAM_POSITION_IN_ARTICLE = "CONTENT_OUTSTREAM_POSITION_IN_ARTICLE";
	var CONTENT_OUTSTREAM_POSITION_IN_BANNER = "CONTENT_OUTSTREAM_POSITION_IN_BANNER";
	var CONTENT_OUTSTREAM_POSITION_IN_FEED = "CONTENT_OUTSTREAM_POSITION_IN_FEED";
	var CONTENT_OUTSTREAM_POSITION_UNKNOWN = "CONTENT_OUTSTREAM_POSITION_UNKNOWN";
	var CONTENT_OUTSTREAM_POSITION_UNSPECIFIED = "CONTENT_OUTSTREAM_POSITION_UNSPECIFIED";
}