package grest.displayvideo.v1.types;
@:enum abstract CreativeConfig_creativeType(String) from String to String to tink.Stringly {
	var CREATIVE_TYPE_AUDIO = "CREATIVE_TYPE_AUDIO";
	var CREATIVE_TYPE_EXPANDABLE = "CREATIVE_TYPE_EXPANDABLE";
	var CREATIVE_TYPE_LIGHTBOX = "CREATIVE_TYPE_LIGHTBOX";
	var CREATIVE_TYPE_NATIVE = "CREATIVE_TYPE_NATIVE";
	var CREATIVE_TYPE_NATIVE_APP_INSTALL = "CREATIVE_TYPE_NATIVE_APP_INSTALL";
	var CREATIVE_TYPE_NATIVE_APP_INSTALL_SQUARE = "CREATIVE_TYPE_NATIVE_APP_INSTALL_SQUARE";
	var CREATIVE_TYPE_NATIVE_SITE_SQUARE = "CREATIVE_TYPE_NATIVE_SITE_SQUARE";
	var CREATIVE_TYPE_NATIVE_VIDEO = "CREATIVE_TYPE_NATIVE_VIDEO";
	var CREATIVE_TYPE_PUBLISHER_HOSTED = "CREATIVE_TYPE_PUBLISHER_HOSTED";
	var CREATIVE_TYPE_STANDARD = "CREATIVE_TYPE_STANDARD";
	var CREATIVE_TYPE_TEMPLATED_APP_INSTALL = "CREATIVE_TYPE_TEMPLATED_APP_INSTALL";
	var CREATIVE_TYPE_TEMPLATED_APP_INSTALL_INTERSTITIAL = "CREATIVE_TYPE_TEMPLATED_APP_INSTALL_INTERSTITIAL";
	var CREATIVE_TYPE_TEMPLATED_APP_INSTALL_VIDEO = "CREATIVE_TYPE_TEMPLATED_APP_INSTALL_VIDEO";
	var CREATIVE_TYPE_UNSPECIFIED = "CREATIVE_TYPE_UNSPECIFIED";
	var CREATIVE_TYPE_VIDEO = "CREATIVE_TYPE_VIDEO";
}