package grest.displayvideo.v1.types;
@:enum abstract Creative_hostingSource(String) from String to String to tink.Stringly {
	var HOSTING_SOURCE_CM = "HOSTING_SOURCE_CM";
	var HOSTING_SOURCE_HOSTED = "HOSTING_SOURCE_HOSTED";
	var HOSTING_SOURCE_RICH_MEDIA = "HOSTING_SOURCE_RICH_MEDIA";
	var HOSTING_SOURCE_THIRD_PARTY = "HOSTING_SOURCE_THIRD_PARTY";
	var HOSTING_SOURCE_UNSPECIFIED = "HOSTING_SOURCE_UNSPECIFIED";
}