package grest.displayvideo.v1.types;
@:enum abstract Creative_expandingDirection(String) from String to String to tink.Stringly {
	var EXPANDING_DIRECTION_ANY_DIAGONAL = "EXPANDING_DIRECTION_ANY_DIAGONAL";
	var EXPANDING_DIRECTION_DOWN = "EXPANDING_DIRECTION_DOWN";
	var EXPANDING_DIRECTION_DOWN_AND_LEFT = "EXPANDING_DIRECTION_DOWN_AND_LEFT";
	var EXPANDING_DIRECTION_DOWN_AND_RIGHT = "EXPANDING_DIRECTION_DOWN_AND_RIGHT";
	var EXPANDING_DIRECTION_LEFT = "EXPANDING_DIRECTION_LEFT";
	var EXPANDING_DIRECTION_LEFT_OR_RIGHT = "EXPANDING_DIRECTION_LEFT_OR_RIGHT";
	var EXPANDING_DIRECTION_NONE = "EXPANDING_DIRECTION_NONE";
	var EXPANDING_DIRECTION_RIGHT = "EXPANDING_DIRECTION_RIGHT";
	var EXPANDING_DIRECTION_UNSPECIFIED = "EXPANDING_DIRECTION_UNSPECIFIED";
	var EXPANDING_DIRECTION_UP = "EXPANDING_DIRECTION_UP";
	var EXPANDING_DIRECTION_UP_AND_LEFT = "EXPANDING_DIRECTION_UP_AND_LEFT";
	var EXPANDING_DIRECTION_UP_AND_RIGHT = "EXPANDING_DIRECTION_UP_AND_RIGHT";
	var EXPANDING_DIRECTION_UP_OR_DOWN = "EXPANDING_DIRECTION_UP_OR_DOWN";
}