package grest.displayvideo.v1.types;
@:enum abstract DigitalContentLabelAssignedTargetingOptionDetails_contentRatingTier(String) from String to String to tink.Stringly {
	var CONTENT_RATING_TIER_GENERAL = "CONTENT_RATING_TIER_GENERAL";
	var CONTENT_RATING_TIER_MATURE = "CONTENT_RATING_TIER_MATURE";
	var CONTENT_RATING_TIER_PARENTAL_GUIDANCE = "CONTENT_RATING_TIER_PARENTAL_GUIDANCE";
	var CONTENT_RATING_TIER_TEENS = "CONTENT_RATING_TIER_TEENS";
	var CONTENT_RATING_TIER_UNRATED = "CONTENT_RATING_TIER_UNRATED";
	var CONTENT_RATING_TIER_UNSPECIFIED = "CONTENT_RATING_TIER_UNSPECIFIED";
}