package grest.displayvideo.v1.types;
@:enum abstract DoubleVerifyVideoViewability_videoViewableRate(String) from String to String to tink.Stringly {
	var VIDEO_VIEWABLE_RATE_UNSPECIFIED = "VIDEO_VIEWABLE_RATE_UNSPECIFIED";
	var VIEWED_PERFORMANCE_10_PERCENT_HIGHER = "VIEWED_PERFORMANCE_10_PERCENT_HIGHER";
	var VIEWED_PERFORMANCE_20_PERCENT_HIGHER = "VIEWED_PERFORMANCE_20_PERCENT_HIGHER";
	var VIEWED_PERFORMANCE_25_PERCENT_HIGHER = "VIEWED_PERFORMANCE_25_PERCENT_HIGHER";
	var VIEWED_PERFORMANCE_30_PERCENT_HIGHER = "VIEWED_PERFORMANCE_30_PERCENT_HIGHER";
	var VIEWED_PERFORMANCE_35_PERCENT_HIGHER = "VIEWED_PERFORMANCE_35_PERCENT_HIGHER";
	var VIEWED_PERFORMANCE_40_PERCENT_HIGHER = "VIEWED_PERFORMANCE_40_PERCENT_HIGHER";
}