package grest.displayvideo.v1.types;
@:enum abstract DoubleVerifyVideoViewability_videoIab(String) from String to String to tink.Stringly {
	var IAB_VIEWABILITY_30_PERCENT_HIHGER = "IAB_VIEWABILITY_30_PERCENT_HIHGER";
	var IAB_VIEWABILITY_40_PERCENT_HIHGER = "IAB_VIEWABILITY_40_PERCENT_HIHGER";
	var IAB_VIEWABILITY_50_PERCENT_HIGHER = "IAB_VIEWABILITY_50_PERCENT_HIGHER";
	var IAB_VIEWABILITY_55_PERCENT_HIHGER = "IAB_VIEWABILITY_55_PERCENT_HIHGER";
	var IAB_VIEWABILITY_60_PERCENT_HIGHER = "IAB_VIEWABILITY_60_PERCENT_HIGHER";
	var IAB_VIEWABILITY_65_PERCENT_HIHGER = "IAB_VIEWABILITY_65_PERCENT_HIHGER";
	var IAB_VIEWABILITY_70_PERCENT_HIGHER = "IAB_VIEWABILITY_70_PERCENT_HIGHER";
	var IAB_VIEWABILITY_75_PERCENT_HIGHER = "IAB_VIEWABILITY_75_PERCENT_HIGHER";
	var IAB_VIEWABILITY_80_PERCENT_HIGHER = "IAB_VIEWABILITY_80_PERCENT_HIGHER";
	var VIDEO_IAB_UNSPECIFIED = "VIDEO_IAB_UNSPECIFIED";
}