package grest.displayvideo.v1.types;
@:enum abstract DoubleVerifyFraudInvalidTraffic_avoidedFraudOption(String) from String to String to tink.Stringly {
	var AD_IMPRESSION_FRAUD_10 = "AD_IMPRESSION_FRAUD_10";
	var AD_IMPRESSION_FRAUD_100 = "AD_IMPRESSION_FRAUD_100";
	var AD_IMPRESSION_FRAUD_2 = "AD_IMPRESSION_FRAUD_2";
	var AD_IMPRESSION_FRAUD_25 = "AD_IMPRESSION_FRAUD_25";
	var AD_IMPRESSION_FRAUD_4 = "AD_IMPRESSION_FRAUD_4";
	var AD_IMPRESSION_FRAUD_50 = "AD_IMPRESSION_FRAUD_50";
	var AD_IMPRESSION_FRAUD_6 = "AD_IMPRESSION_FRAUD_6";
	var AD_IMPRESSION_FRAUD_8 = "AD_IMPRESSION_FRAUD_8";
	var FRAUD_UNSPECIFIED = "FRAUD_UNSPECIFIED";
}