package grest.displayvideo.v1.types;
@:enum abstract DoubleVerifyDisplayViewability_iab(String) from String to String to tink.Stringly {
	var IAB_VIEWED_RATE_30_PERCENT_HIGHER = "IAB_VIEWED_RATE_30_PERCENT_HIGHER";
	var IAB_VIEWED_RATE_40_PERCENT_HIGHER = "IAB_VIEWED_RATE_40_PERCENT_HIGHER";
	var IAB_VIEWED_RATE_50_PERCENT_HIGHER = "IAB_VIEWED_RATE_50_PERCENT_HIGHER";
	var IAB_VIEWED_RATE_55_PERCENT_HIGHER = "IAB_VIEWED_RATE_55_PERCENT_HIGHER";
	var IAB_VIEWED_RATE_60_PERCENT_HIGHER = "IAB_VIEWED_RATE_60_PERCENT_HIGHER";
	var IAB_VIEWED_RATE_65_PERCENT_HIGHER = "IAB_VIEWED_RATE_65_PERCENT_HIGHER";
	var IAB_VIEWED_RATE_70_PERCENT_HIGHER = "IAB_VIEWED_RATE_70_PERCENT_HIGHER";
	var IAB_VIEWED_RATE_75_PERCENT_HIGHER = "IAB_VIEWED_RATE_75_PERCENT_HIGHER";
	var IAB_VIEWED_RATE_80_PERCENT_HIGHER = "IAB_VIEWED_RATE_80_PERCENT_HIGHER";
	var IAB_VIEWED_RATE_UNSPECIFIED = "IAB_VIEWED_RATE_UNSPECIFIED";
}