package grest.displayvideo.v1.types;
@:enum abstract FirstAndThirdPartyAudience_firstAndThirdPartyAudienceType(String) from String to String to tink.Stringly {
	var FIRST_AND_THIRD_PARTY_AUDIENCE_TYPE_FIRST_PARTY = "FIRST_AND_THIRD_PARTY_AUDIENCE_TYPE_FIRST_PARTY";
	var FIRST_AND_THIRD_PARTY_AUDIENCE_TYPE_THIRD_PARTY = "FIRST_AND_THIRD_PARTY_AUDIENCE_TYPE_THIRD_PARTY";
	var FIRST_AND_THIRD_PARTY_AUDIENCE_TYPE_UNSPECIFIED = "FIRST_AND_THIRD_PARTY_AUDIENCE_TYPE_UNSPECIFIED";
}