package grest.displayvideo.v1.types;
@:enum abstract FirstAndThirdPartyAudience_audienceType(String) from String to String to tink.Stringly {
	var ACTIVITY_BASED = "ACTIVITY_BASED";
	var AUDIENCE_TYPE_UNSPECIFIED = "AUDIENCE_TYPE_UNSPECIFIED";
	var CUSTOMER_MATCH_CONTACT_INFO = "CUSTOMER_MATCH_CONTACT_INFO";
	var CUSTOMER_MATCH_DEVICE_ID = "CUSTOMER_MATCH_DEVICE_ID";
	var CUSTOMER_MATCH_USER_ID = "CUSTOMER_MATCH_USER_ID";
	var FREQUENCY_CAP = "FREQUENCY_CAP";
	var LICENSED = "LICENSED";
	var TAG_BASED = "TAG_BASED";
	var YOUTUBE_USERS = "YOUTUBE_USERS";
}