package grest.displayvideo.v1.types;
@:enum abstract GoogleAudience_googleAudienceType(String) from String to String to tink.Stringly {
	var GOOGLE_AUDIENCE_TYPE_AFFINITY = "GOOGLE_AUDIENCE_TYPE_AFFINITY";
	var GOOGLE_AUDIENCE_TYPE_EXTENDED_DEMOGRAPHIC = "GOOGLE_AUDIENCE_TYPE_EXTENDED_DEMOGRAPHIC";
	var GOOGLE_AUDIENCE_TYPE_INSTALLED_APPS = "GOOGLE_AUDIENCE_TYPE_INSTALLED_APPS";
	var GOOGLE_AUDIENCE_TYPE_IN_MARKET = "GOOGLE_AUDIENCE_TYPE_IN_MARKET";
	var GOOGLE_AUDIENCE_TYPE_LIFE_EVENT = "GOOGLE_AUDIENCE_TYPE_LIFE_EVENT";
	var GOOGLE_AUDIENCE_TYPE_NEW_MOBILE_DEVICES = "GOOGLE_AUDIENCE_TYPE_NEW_MOBILE_DEVICES";
	var GOOGLE_AUDIENCE_TYPE_UNSPECIFIED = "GOOGLE_AUDIENCE_TYPE_UNSPECIFIED";
}