package grest.displayvideo.v1.types;
@:enum abstract HouseholdIncomeTargetingOptionDetails_householdIncome(String) from String to String to tink.Stringly {
	var HOUSEHOLD_INCOME_LOWER_50_PERCENT = "HOUSEHOLD_INCOME_LOWER_50_PERCENT";
	var HOUSEHOLD_INCOME_TOP_10_PERCENT = "HOUSEHOLD_INCOME_TOP_10_PERCENT";
	var HOUSEHOLD_INCOME_TOP_11_TO_20_PERCENT = "HOUSEHOLD_INCOME_TOP_11_TO_20_PERCENT";
	var HOUSEHOLD_INCOME_TOP_21_TO_30_PERCENT = "HOUSEHOLD_INCOME_TOP_21_TO_30_PERCENT";
	var HOUSEHOLD_INCOME_TOP_31_TO_40_PERCENT = "HOUSEHOLD_INCOME_TOP_31_TO_40_PERCENT";
	var HOUSEHOLD_INCOME_TOP_41_TO_50_PERCENT = "HOUSEHOLD_INCOME_TOP_41_TO_50_PERCENT";
	var HOUSEHOLD_INCOME_UNKNOWN = "HOUSEHOLD_INCOME_UNKNOWN";
	var HOUSEHOLD_INCOME_UNSPECIFIED = "HOUSEHOLD_INCOME_UNSPECIFIED";
}