package grest.displayvideo.v1.types;
@:enum abstract InsertionOrderBudget_automationType(String) from String to String to tink.Stringly {
	var INSERTION_ORDER_AUTOMATION_TYPE_BID_BUDGET = "INSERTION_ORDER_AUTOMATION_TYPE_BID_BUDGET";
	var INSERTION_ORDER_AUTOMATION_TYPE_BUDGET = "INSERTION_ORDER_AUTOMATION_TYPE_BUDGET";
	var INSERTION_ORDER_AUTOMATION_TYPE_NONE = "INSERTION_ORDER_AUTOMATION_TYPE_NONE";
	var INSERTION_ORDER_AUTOMATION_TYPE_UNSPECIFIED = "INSERTION_ORDER_AUTOMATION_TYPE_UNSPECIFIED";
}