package grest.displayvideo.v1.types;
@:enum abstract IntegralAdScience_displayViewability(String) from String to String to tink.Stringly {
	var PERFORMANCE_VIEWABILITY_40 = "PERFORMANCE_VIEWABILITY_40";
	var PERFORMANCE_VIEWABILITY_50 = "PERFORMANCE_VIEWABILITY_50";
	var PERFORMANCE_VIEWABILITY_60 = "PERFORMANCE_VIEWABILITY_60";
	var PERFORMANCE_VIEWABILITY_70 = "PERFORMANCE_VIEWABILITY_70";
	var PERFORMANCE_VIEWABILITY_UNSPECIFIED = "PERFORMANCE_VIEWABILITY_UNSPECIFIED";
}