package grest.displayvideo.v1.types;
@:enum abstract InventorySource_commitment(String) from String to String to tink.Stringly {
	var INVENTORY_SOURCE_COMMITMENT_GUARANTEED = "INVENTORY_SOURCE_COMMITMENT_GUARANTEED";
	var INVENTORY_SOURCE_COMMITMENT_NON_GUARANTEED = "INVENTORY_SOURCE_COMMITMENT_NON_GUARANTEED";
	var INVENTORY_SOURCE_COMMITMENT_UNSPECIFIED = "INVENTORY_SOURCE_COMMITMENT_UNSPECIFIED";
}