package grest.displayvideo.v1.types;
@:enum abstract InventorySource_deliveryMethod(String) from String to String to tink.Stringly {
	var INVENTORY_SOURCE_DELIVERY_METHOD_PROGRAMMATIC = "INVENTORY_SOURCE_DELIVERY_METHOD_PROGRAMMATIC";
	var INVENTORY_SOURCE_DELIVERY_METHOD_TAG = "INVENTORY_SOURCE_DELIVERY_METHOD_TAG";
	var INVENTORY_SOURCE_DELIVERY_METHOD_UNSPECIFIED = "INVENTORY_SOURCE_DELIVERY_METHOD_UNSPECIFIED";
}