package grest.displayvideo.v1.types;
@:enum abstract InventorySourceStatus_configStatus(String) from String to String to tink.Stringly {
	var INVENTORY_SOURCE_CONFIG_STATUS_COMPLETED = "INVENTORY_SOURCE_CONFIG_STATUS_COMPLETED";
	var INVENTORY_SOURCE_CONFIG_STATUS_PENDING = "INVENTORY_SOURCE_CONFIG_STATUS_PENDING";
	var INVENTORY_SOURCE_CONFIG_STATUS_UNSPECIFIED = "INVENTORY_SOURCE_CONFIG_STATUS_UNSPECIFIED";
}