package grest.displayvideo.v1.types;
@:enum abstract LineItemBudget_budgetAllocationType(String) from String to String to tink.Stringly {
	var LINE_ITEM_BUDGET_ALLOCATION_TYPE_AUTOMATIC = "LINE_ITEM_BUDGET_ALLOCATION_TYPE_AUTOMATIC";
	var LINE_ITEM_BUDGET_ALLOCATION_TYPE_FIXED = "LINE_ITEM_BUDGET_ALLOCATION_TYPE_FIXED";
	var LINE_ITEM_BUDGET_ALLOCATION_TYPE_UNLIMITED = "LINE_ITEM_BUDGET_ALLOCATION_TYPE_UNLIMITED";
	var LINE_ITEM_BUDGET_ALLOCATION_TYPE_UNSPECIFIED = "LINE_ITEM_BUDGET_ALLOCATION_TYPE_UNSPECIFIED";
}