package grest.displayvideo.v1.types;
@:enum abstract LineItemFlight_flightDateType(String) from String to String to tink.Stringly {
	var LINE_ITEM_FLIGHT_DATE_TYPE_CUSTOM = "LINE_ITEM_FLIGHT_DATE_TYPE_CUSTOM";
	var LINE_ITEM_FLIGHT_DATE_TYPE_INHERITED = "LINE_ITEM_FLIGHT_DATE_TYPE_INHERITED";
	var LINE_ITEM_FLIGHT_DATE_TYPE_TRIGGER = "LINE_ITEM_FLIGHT_DATE_TYPE_TRIGGER";
	var LINE_ITEM_FLIGHT_DATE_TYPE_UNSPECIFIED = "LINE_ITEM_FLIGHT_DATE_TYPE_UNSPECIFIED";
}