package grest.displayvideo.v1.types;
typedef LineItem = {
	/**
		Output only. The unique ID of the advertiser the line item belongs to.
	**/
	@:optional
	var advertiserId : String;
	/**
		Required. The bidding strategy of the line item.
	**/
	@:optional
	var bidStrategy : BiddingStrategy;
	/**
		Required. The budget allocation setting of the line item.
	**/
	@:optional
	var budget : LineItemBudget;
	/**
		Output only. The unique ID of the campaign that the line item belongs to.
	**/
	@:optional
	var campaignId : String;
	/**
		The conversion tracking setting of the line item.
	**/
	@:optional
	var conversionCounting : ConversionCountingConfig;
	/**
		The IDs of the creatives associated with the line item.
	**/
	@:optional
	var creativeIds : Array<String>;
	/**
		Required. The display name of the line item. Must be UTF-8 encoded with a maximum size of 240 bytes.
	**/
	@:optional
	var displayName : String;
	/**
		Required. Controls whether or not the line item can spend its budget and bid on inventory. * For CreateLineItem method, only `ENTITY_STATUS_DRAFT` is allowed. To activate a line item, use UpdateLineItem method and update the status to `ENTITY_STATUS_ACTIVE` after creation. * A line item cannot be changed back to `ENTITY_STATUS_DRAFT` status from any other status. * If the line item's parent insertion order is not active, the line item can't spend its budget even if its own status is `ENTITY_STATUS_ACTIVE`.
	**/
	@:optional
	var entityStatus : grest.displayvideo.v1.types.LineItem_entityStatus;
	/**
		Required. The start and end time of the line item's flight.
	**/
	@:optional
	var flight : LineItemFlight;
	/**
		Required. The frequency capping setting of the line item.
	**/
	@:optional
	var frequencyCap : FrequencyCap;
	/**
		Required. Immutable. The unique ID of the insertion order that the line item belongs to.
	**/
	@:optional
	var insertionOrderId : String;
	/**
		Integration details of the line item.
	**/
	@:optional
	var integrationDetails : IntegrationDetails;
	/**
		The IDs of the private inventory sources assigned to the line item.
	**/
	@:optional
	var inventorySourceIds : Array<String>;
	/**
		Output only. The unique ID of the line item. Assigned by the system.
	**/
	@:optional
	var lineItemId : String;
	/**
		Required. Immutable. The type of the line item.
	**/
	@:optional
	var lineItemType : grest.displayvideo.v1.types.LineItem_lineItemType;
	/**
		The mobile app promoted by the line item. This is applicable only when line_item_type is either `LINE_ITEM_TYPE_DISPLAY_MOBILE_APP_INSTALL` or `LINE_ITEM_TYPE_VIDEO_MOBILE_APP_INSTALL`.
	**/
	@:optional
	var mobileApp : MobileApp;
	/**
		Output only. The resource name of the line item.
	**/
	@:optional
	var name : String;
	/**
		Required. The budget spending speed setting of the line item.
	**/
	@:optional
	var pacing : Pacing;
	/**
		The partner costs associated with the line item. If absent or empty in CreateLineItem method, the newly created line item will inherit partner costs from its parent insertion order.
	**/
	@:optional
	var partnerCosts : Array<PartnerCost>;
	/**
		Required. The partner revenue model setting of the line item.
	**/
	@:optional
	var partnerRevenueModel : PartnerRevenueModel;
	/**
		The [targeting expansion](https://support.google.com/displayvideo/answer/10191558) settings of the line item. This config is only applicable when eligible audience list targeting is assigned to the line item.
	**/
	@:optional
	var targetingExpansion : TargetingExpansionConfig;
	/**
		Output only. The timestamp when the line item was last updated. Assigned by the system.
	**/
	@:optional
	var updateTime : String;
	/**
		Output only. The warning messages generated by the line item. These warnings do not block saving the line item, but some may block the line item from running.
	**/
	@:optional
	var warningMessages : Array<String>;
}