package grest.displayvideo.v1.types;
@:enum abstract ObaIcon_position(String) from String to String to tink.Stringly {
	var OBA_ICON_POSITION_LOWER_LEFT = "OBA_ICON_POSITION_LOWER_LEFT";
	var OBA_ICON_POSITION_LOWER_RIGHT = "OBA_ICON_POSITION_LOWER_RIGHT";
	var OBA_ICON_POSITION_UNSPECIFIED = "OBA_ICON_POSITION_UNSPECIFIED";
	var OBA_ICON_POSITION_UPPER_LEFT = "OBA_ICON_POSITION_UPPER_LEFT";
	var OBA_ICON_POSITION_UPPER_RIGHT = "OBA_ICON_POSITION_UPPER_RIGHT";
}