package grest.displayvideo.v1.types;
@:enum abstract ParentEntityFilter_filterType(String) from String to String to tink.Stringly {
	var FILTER_TYPE_ADVERTISER_ID = "FILTER_TYPE_ADVERTISER_ID";
	var FILTER_TYPE_CAMPAIGN_ID = "FILTER_TYPE_CAMPAIGN_ID";
	var FILTER_TYPE_INSERTION_ORDER_ID = "FILTER_TYPE_INSERTION_ORDER_ID";
	var FILTER_TYPE_LINE_ITEM_ID = "FILTER_TYPE_LINE_ITEM_ID";
	var FILTER_TYPE_MEDIA_PRODUCT_ID = "FILTER_TYPE_MEDIA_PRODUCT_ID";
	var FILTER_TYPE_NONE = "FILTER_TYPE_NONE";
	var FILTER_TYPE_UNSPECIFIED = "FILTER_TYPE_UNSPECIFIED";
}