package grest.displayvideo.v1.types;
@:enum abstract PartnerRevenueModel_markupType(String) from String to String to tink.Stringly {
	var PARTNER_REVENUE_MODEL_MARKUP_TYPE_CPM = "PARTNER_REVENUE_MODEL_MARKUP_TYPE_CPM";
	var PARTNER_REVENUE_MODEL_MARKUP_TYPE_MEDIA_COST_MARKUP = "PARTNER_REVENUE_MODEL_MARKUP_TYPE_MEDIA_COST_MARKUP";
	var PARTNER_REVENUE_MODEL_MARKUP_TYPE_TOTAL_MEDIA_COST_MARKUP = "PARTNER_REVENUE_MODEL_MARKUP_TYPE_TOTAL_MEDIA_COST_MARKUP";
	var PARTNER_REVENUE_MODEL_MARKUP_TYPE_UNSPECIFIED = "PARTNER_REVENUE_MODEL_MARKUP_TYPE_UNSPECIFIED";
}