package grest.displayvideo.v1.types;
@:enum abstract PerformanceGoal_performanceGoalType(String) from String to String to tink.Stringly {
	var PERFORMANCE_GOAL_TYPE_AUDIO_COMPLETION_RATE = "PERFORMANCE_GOAL_TYPE_AUDIO_COMPLETION_RATE";
	var PERFORMANCE_GOAL_TYPE_CLICK_CVR = "PERFORMANCE_GOAL_TYPE_CLICK_CVR";
	var PERFORMANCE_GOAL_TYPE_CPA = "PERFORMANCE_GOAL_TYPE_CPA";
	var PERFORMANCE_GOAL_TYPE_CPC = "PERFORMANCE_GOAL_TYPE_CPC";
	var PERFORMANCE_GOAL_TYPE_CPE = "PERFORMANCE_GOAL_TYPE_CPE";
	var PERFORMANCE_GOAL_TYPE_CPIAVC = "PERFORMANCE_GOAL_TYPE_CPIAVC";
	var PERFORMANCE_GOAL_TYPE_CPM = "PERFORMANCE_GOAL_TYPE_CPM";
	var PERFORMANCE_GOAL_TYPE_CTR = "PERFORMANCE_GOAL_TYPE_CTR";
	var PERFORMANCE_GOAL_TYPE_IMPRESSION_CVR = "PERFORMANCE_GOAL_TYPE_IMPRESSION_CVR";
	var PERFORMANCE_GOAL_TYPE_OTHER = "PERFORMANCE_GOAL_TYPE_OTHER";
	var PERFORMANCE_GOAL_TYPE_UNSPECIFIED = "PERFORMANCE_GOAL_TYPE_UNSPECIFIED";
	var PERFORMANCE_GOAL_TYPE_VCPM = "PERFORMANCE_GOAL_TYPE_VCPM";
	var PERFORMANCE_GOAL_TYPE_VIDEO_COMPLETION_RATE = "PERFORMANCE_GOAL_TYPE_VIDEO_COMPLETION_RATE";
	var PERFORMANCE_GOAL_TYPE_VIEWABILITY = "PERFORMANCE_GOAL_TYPE_VIEWABILITY";
	var PERFORMANCE_GOAL_TYPE_VTR = "PERFORMANCE_GOAL_TYPE_VTR";
}