package grest.displayvideo.v1.types;
@:enum abstract RateDetails_inventorySourceRateType(String) from String to String to tink.Stringly {
	var INVENTORY_SOURCE_RATE_TYPE_CPD = "INVENTORY_SOURCE_RATE_TYPE_CPD";
	var INVENTORY_SOURCE_RATE_TYPE_CPM_FIXED = "INVENTORY_SOURCE_RATE_TYPE_CPM_FIXED";
	var INVENTORY_SOURCE_RATE_TYPE_CPM_FLOOR = "INVENTORY_SOURCE_RATE_TYPE_CPM_FLOOR";
	var INVENTORY_SOURCE_RATE_TYPE_FLAT = "INVENTORY_SOURCE_RATE_TYPE_FLAT";
	var INVENTORY_SOURCE_RATE_TYPE_UNSPECIFIED = "INVENTORY_SOURCE_RATE_TYPE_UNSPECIFIED";
}