package grest.displayvideo.v1.types;
@:enum abstract ReviewStatusInfo_approvalStatus(String) from String to String to tink.Stringly {
	var APPROVAL_STATUS_APPROVED_SERVABLE = "APPROVAL_STATUS_APPROVED_SERVABLE";
	var APPROVAL_STATUS_PENDING_NOT_SERVABLE = "APPROVAL_STATUS_PENDING_NOT_SERVABLE";
	var APPROVAL_STATUS_PENDING_SERVABLE = "APPROVAL_STATUS_PENDING_SERVABLE";
	var APPROVAL_STATUS_REJECTED_NOT_SERVABLE = "APPROVAL_STATUS_REJECTED_NOT_SERVABLE";
	var APPROVAL_STATUS_UNSPECIFIED = "APPROVAL_STATUS_UNSPECIFIED";
}