package grest.displayvideo.v1.types;
@:enum abstract SensitiveCategoryTargetingOptionDetails_sensitiveCategory(String) from String to String to tink.Stringly {
	var SENSITIVE_CATEGORY_ADULT = "SENSITIVE_CATEGORY_ADULT";
	var SENSITIVE_CATEGORY_ALCOHOL = "SENSITIVE_CATEGORY_ALCOHOL";
	var SENSITIVE_CATEGORY_DEROGATORY = "SENSITIVE_CATEGORY_DEROGATORY";
	var SENSITIVE_CATEGORY_DOWNLOADS_SHARING = "SENSITIVE_CATEGORY_DOWNLOADS_SHARING";
	var SENSITIVE_CATEGORY_DRUGS = "SENSITIVE_CATEGORY_DRUGS";
	var SENSITIVE_CATEGORY_GAMBLING = "SENSITIVE_CATEGORY_GAMBLING";
	var SENSITIVE_CATEGORY_POLITICS = "SENSITIVE_CATEGORY_POLITICS";
	var SENSITIVE_CATEGORY_PROFANITY = "SENSITIVE_CATEGORY_PROFANITY";
	var SENSITIVE_CATEGORY_RELIGION = "SENSITIVE_CATEGORY_RELIGION";
	var SENSITIVE_CATEGORY_SENSITIVE_SOCIAL_ISSUES = "SENSITIVE_CATEGORY_SENSITIVE_SOCIAL_ISSUES";
	var SENSITIVE_CATEGORY_SHOCKING = "SENSITIVE_CATEGORY_SHOCKING";
	var SENSITIVE_CATEGORY_SUGGESTIVE = "SENSITIVE_CATEGORY_SUGGESTIVE";
	var SENSITIVE_CATEGORY_TOBACCO = "SENSITIVE_CATEGORY_TOBACCO";
	var SENSITIVE_CATEGORY_TRAGEDY = "SENSITIVE_CATEGORY_TRAGEDY";
	var SENSITIVE_CATEGORY_TRANSPORTATION_ACCIDENTS = "SENSITIVE_CATEGORY_TRANSPORTATION_ACCIDENTS";
	var SENSITIVE_CATEGORY_UNSPECIFIED = "SENSITIVE_CATEGORY_UNSPECIFIED";
	var SENSITIVE_CATEGORY_VIOLENCE = "SENSITIVE_CATEGORY_VIOLENCE";
	var SENSITIVE_CATEGORY_WEAPONS = "SENSITIVE_CATEGORY_WEAPONS";
}