package grest.displayvideo.v1.types;
@:enum abstract ThirdPartyUrl_type(String) from String to String to tink.Stringly {
	var THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_COMPLETE = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_COMPLETE";
	var THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_CUSTOM = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_CUSTOM";
	var THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_FIRST_QUARTILE = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_FIRST_QUARTILE";
	var THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_FULLSCREEN = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_FULLSCREEN";
	var THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_MIDPOINT = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_MIDPOINT";
	var THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_MUTE = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_MUTE";
	var THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_PAUSE = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_PAUSE";
	var THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_PROGRESS = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_PROGRESS";
	var THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_REWIND = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_REWIND";
	var THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_SKIP = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_SKIP";
	var THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_START = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_START";
	var THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_STOP = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_STOP";
	var THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_THIRD_QUARTILE = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_THIRD_QUARTILE";
	var THIRD_PARTY_URL_TYPE_CLICK_TRACKING = "THIRD_PARTY_URL_TYPE_CLICK_TRACKING";
	var THIRD_PARTY_URL_TYPE_IMPRESSION = "THIRD_PARTY_URL_TYPE_IMPRESSION";
	var THIRD_PARTY_URL_TYPE_UNSPECIFIED = "THIRD_PARTY_URL_TYPE_UNSPECIFIED";
}