package grest.displayvideo.v1.types;
@:enum abstract UniversalAdId_registry(String) from String to String to tink.Stringly {
	var UNIVERSAL_AD_REGISTRY_AD_ID = "UNIVERSAL_AD_REGISTRY_AD_ID";
	var UNIVERSAL_AD_REGISTRY_CLEARCAST = "UNIVERSAL_AD_REGISTRY_CLEARCAST";
	var UNIVERSAL_AD_REGISTRY_CM = "UNIVERSAL_AD_REGISTRY_CM";
	var UNIVERSAL_AD_REGISTRY_DV360 = "UNIVERSAL_AD_REGISTRY_DV360";
	var UNIVERSAL_AD_REGISTRY_OTHER = "UNIVERSAL_AD_REGISTRY_OTHER";
	var UNIVERSAL_AD_REGISTRY_UNSPECIFIED = "UNIVERSAL_AD_REGISTRY_UNSPECIFIED";
}