package grest.displayvideo.v1.types;
@:enum abstract ViewabilityAssignedTargetingOptionDetails_viewability(String) from String to String to tink.Stringly {
	var VIEWABILITY_10_PERCENT_OR_MORE = "VIEWABILITY_10_PERCENT_OR_MORE";
	var VIEWABILITY_20_PERCENT_OR_MORE = "VIEWABILITY_20_PERCENT_OR_MORE";
	var VIEWABILITY_30_PERCENT_OR_MORE = "VIEWABILITY_30_PERCENT_OR_MORE";
	var VIEWABILITY_40_PERCENT_OR_MORE = "VIEWABILITY_40_PERCENT_OR_MORE";
	var VIEWABILITY_50_PERCENT_OR_MORE = "VIEWABILITY_50_PERCENT_OR_MORE";
	var VIEWABILITY_60_PERCENT_OR_MORE = "VIEWABILITY_60_PERCENT_OR_MORE";
	var VIEWABILITY_70_PERCENT_OR_MORE = "VIEWABILITY_70_PERCENT_OR_MORE";
	var VIEWABILITY_80_PERCENT_OR_MORE = "VIEWABILITY_80_PERCENT_OR_MORE";
	var VIEWABILITY_90_PERCENT_OR_MORE = "VIEWABILITY_90_PERCENT_OR_MORE";
	var VIEWABILITY_UNSPECIFIED = "VIEWABILITY_UNSPECIFIED";
}