package grest.monitoring.v3.types;
@:enum abstract Aggregation_crossSeriesReducer(String) from String to String to tink.Stringly {
	var REDUCE_COUNT = "REDUCE_COUNT";
	var REDUCE_COUNT_FALSE = "REDUCE_COUNT_FALSE";
	var REDUCE_COUNT_TRUE = "REDUCE_COUNT_TRUE";
	var REDUCE_FRACTION_TRUE = "REDUCE_FRACTION_TRUE";
	var REDUCE_MAX = "REDUCE_MAX";
	var REDUCE_MEAN = "REDUCE_MEAN";
	var REDUCE_MIN = "REDUCE_MIN";
	var REDUCE_NONE = "REDUCE_NONE";
	var REDUCE_PERCENTILE_05 = "REDUCE_PERCENTILE_05";
	var REDUCE_PERCENTILE_50 = "REDUCE_PERCENTILE_50";
	var REDUCE_PERCENTILE_95 = "REDUCE_PERCENTILE_95";
	var REDUCE_PERCENTILE_99 = "REDUCE_PERCENTILE_99";
	var REDUCE_STDDEV = "REDUCE_STDDEV";
	var REDUCE_SUM = "REDUCE_SUM";
}