package grest.monitoring.v3.types;
@:enum abstract Api_TimeSeries_list_secondaryAggregation.perSeriesAligner(String) from String to String to tink.Stringly {
	var ALIGN_COUNT = "ALIGN_COUNT";
	var ALIGN_COUNT_FALSE = "ALIGN_COUNT_FALSE";
	var ALIGN_COUNT_TRUE = "ALIGN_COUNT_TRUE";
	var ALIGN_DELTA = "ALIGN_DELTA";
	var ALIGN_FRACTION_TRUE = "ALIGN_FRACTION_TRUE";
	var ALIGN_INTERPOLATE = "ALIGN_INTERPOLATE";
	var ALIGN_MAX = "ALIGN_MAX";
	var ALIGN_MEAN = "ALIGN_MEAN";
	var ALIGN_MIN = "ALIGN_MIN";
	var ALIGN_NEXT_OLDER = "ALIGN_NEXT_OLDER";
	var ALIGN_NONE = "ALIGN_NONE";
	var ALIGN_PERCENTILE_05 = "ALIGN_PERCENTILE_05";
	var ALIGN_PERCENTILE_50 = "ALIGN_PERCENTILE_50";
	var ALIGN_PERCENTILE_95 = "ALIGN_PERCENTILE_95";
	var ALIGN_PERCENTILE_99 = "ALIGN_PERCENTILE_99";
	var ALIGN_PERCENT_CHANGE = "ALIGN_PERCENT_CHANGE";
	var ALIGN_RATE = "ALIGN_RATE";
	var ALIGN_STDDEV = "ALIGN_STDDEV";
	var ALIGN_SUM = "ALIGN_SUM";
}