package grest.websecurityscanner.v1.types;
typedef Xss = {
	/**
		The attack vector of the payload triggering this XSS.
	**/
	@:optional
	var attackVector : grest.websecurityscanner.v1.types.Xss_attackVector;
	/**
		An error message generated by a javascript breakage.
	**/
	@:optional
	var errorMessage : String;
	/**
		Stack traces leading to the point where the XSS occurred.
	**/
	@:optional
	var stackTraces : Array<String>;
	/**
		The reproduction url for the seeding POST request of a Stored XSS.
	**/
	@:optional
	var storedXssSeedingUrl : String;
}