package grest.slides.v1.types;
@:enum abstract CreateParagraphBulletsRequest_bulletPreset(String) from String to String to tink.Stringly {
	var BULLET_ARROW3D_CIRCLE_SQUARE = "BULLET_ARROW3D_CIRCLE_SQUARE";
	var BULLET_ARROW_DIAMOND_DISC = "BULLET_ARROW_DIAMOND_DISC";
	var BULLET_CHECKBOX = "BULLET_CHECKBOX";
	var BULLET_DIAMONDX_ARROW3D_SQUARE = "BULLET_DIAMONDX_ARROW3D_SQUARE";
	var BULLET_DIAMONDX_HOLLOWDIAMOND_SQUARE = "BULLET_DIAMONDX_HOLLOWDIAMOND_SQUARE";
	var BULLET_DIAMOND_CIRCLE_SQUARE = "BULLET_DIAMOND_CIRCLE_SQUARE";
	var BULLET_DISC_CIRCLE_SQUARE = "BULLET_DISC_CIRCLE_SQUARE";
	var BULLET_LEFTTRIANGLE_DIAMOND_DISC = "BULLET_LEFTTRIANGLE_DIAMOND_DISC";
	var BULLET_STAR_CIRCLE_SQUARE = "BULLET_STAR_CIRCLE_SQUARE";
	var NUMBERED_DIGIT_ALPHA_ROMAN = "NUMBERED_DIGIT_ALPHA_ROMAN";
	var NUMBERED_DIGIT_ALPHA_ROMAN_PARENS = "NUMBERED_DIGIT_ALPHA_ROMAN_PARENS";
	var NUMBERED_DIGIT_NESTED = "NUMBERED_DIGIT_NESTED";
	var NUMBERED_UPPERALPHA_ALPHA_ROMAN = "NUMBERED_UPPERALPHA_ALPHA_ROMAN";
	var NUMBERED_UPPERROMAN_UPPERALPHA_DIGIT = "NUMBERED_UPPERROMAN_UPPERALPHA_DIGIT";
	var NUMBERED_ZERODIGIT_ALPHA_ROMAN = "NUMBERED_ZERODIGIT_ALPHA_ROMAN";
}