package grest.slides.v1.types;
@:enum abstract LayoutReference_predefinedLayout(String) from String to String to tink.Stringly {
	var BIG_NUMBER = "BIG_NUMBER";
	var BLANK = "BLANK";
	var CAPTION_ONLY = "CAPTION_ONLY";
	var MAIN_POINT = "MAIN_POINT";
	var ONE_COLUMN_TEXT = "ONE_COLUMN_TEXT";
	var PREDEFINED_LAYOUT_UNSPECIFIED = "PREDEFINED_LAYOUT_UNSPECIFIED";
	var SECTION_HEADER = "SECTION_HEADER";
	var SECTION_TITLE_AND_DESCRIPTION = "SECTION_TITLE_AND_DESCRIPTION";
	var TITLE = "TITLE";
	var TITLE_AND_BODY = "TITLE_AND_BODY";
	var TITLE_AND_TWO_COLUMNS = "TITLE_AND_TWO_COLUMNS";
	var TITLE_ONLY = "TITLE_ONLY";
}