package grest.slides.v1.types;
@:enum abstract Line_lineType(String) from String to String to tink.Stringly {
	var BENT_CONNECTOR_2 = "BENT_CONNECTOR_2";
	var BENT_CONNECTOR_3 = "BENT_CONNECTOR_3";
	var BENT_CONNECTOR_4 = "BENT_CONNECTOR_4";
	var BENT_CONNECTOR_5 = "BENT_CONNECTOR_5";
	var CURVED_CONNECTOR_2 = "CURVED_CONNECTOR_2";
	var CURVED_CONNECTOR_3 = "CURVED_CONNECTOR_3";
	var CURVED_CONNECTOR_4 = "CURVED_CONNECTOR_4";
	var CURVED_CONNECTOR_5 = "CURVED_CONNECTOR_5";
	var STRAIGHT_CONNECTOR_1 = "STRAIGHT_CONNECTOR_1";
	var STRAIGHT_LINE = "STRAIGHT_LINE";
	var TYPE_UNSPECIFIED = "TYPE_UNSPECIFIED";
}