package grest.classroom.v1.types;
typedef Topic = {
	/**
		Identifier of the course. Read-only.
	**/
	@:optional
	var courseId : String;
	/**
		The name of the topic, generated by the user. Leading and trailing whitespaces, if any, are trimmed. Also, multiple consecutive whitespaces are collapsed into one inside the name. The result must be a non-empty string. Topic names are case sensitive, and must be no longer than 100 characters.
	**/
	@:optional
	var name : String;
	/**
		Unique identifier for the topic. Read-only.
	**/
	@:optional
	var topicId : String;
	/**
		The time the topic was last updated by the system. Read-only.
	**/
	@:optional
	var updateTime : String;
}