package grest.dataflow.v1b3.types;
@:enum abstract DerivedSource_derivationMode(String) from String to String to tink.Stringly {
	var SOURCE_DERIVATION_MODE_CHILD_OF_CURRENT = "SOURCE_DERIVATION_MODE_CHILD_OF_CURRENT";
	var SOURCE_DERIVATION_MODE_INDEPENDENT = "SOURCE_DERIVATION_MODE_INDEPENDENT";
	var SOURCE_DERIVATION_MODE_SIBLING_OF_CURRENT = "SOURCE_DERIVATION_MODE_SIBLING_OF_CURRENT";
	var SOURCE_DERIVATION_MODE_UNKNOWN = "SOURCE_DERIVATION_MODE_UNKNOWN";
}