package grest.dataflow.v1b3.types;
typedef InstructionOutput = {
	/**
		The codec to use to encode data being written via this output.
	**/
	@:optional
	var codec : haxe.DynamicAccess<tink.json.Value>;
	/**
		The user-provided name of this output.
	**/
	@:optional
	var name : String;
	/**
		For system-generated byte and mean byte metrics, certain instructions should only report the key size.
	**/
	@:optional
	var onlyCountKeyBytes : Bool;
	/**
		For system-generated byte and mean byte metrics, certain instructions should only report the value size.
	**/
	@:optional
	var onlyCountValueBytes : Bool;
	/**
		System-defined name for this output in the original workflow graph. Outputs that do not contribute to an original instruction do not set this.
	**/
	@:optional
	var originalName : String;
	/**
		System-defined name of this output. Unique across the workflow.
	**/
	@:optional
	var systemName : String;
}