package grest.dataflow.v1b3.types;
@:enum abstract Job_currentState(String) from String to String to tink.Stringly {
	var JOB_STATE_CANCELLED = "JOB_STATE_CANCELLED";
	var JOB_STATE_CANCELLING = "JOB_STATE_CANCELLING";
	var JOB_STATE_DONE = "JOB_STATE_DONE";
	var JOB_STATE_DRAINED = "JOB_STATE_DRAINED";
	var JOB_STATE_DRAINING = "JOB_STATE_DRAINING";
	var JOB_STATE_FAILED = "JOB_STATE_FAILED";
	var JOB_STATE_PENDING = "JOB_STATE_PENDING";
	var JOB_STATE_QUEUED = "JOB_STATE_QUEUED";
	var JOB_STATE_RESOURCE_CLEANING_UP = "JOB_STATE_RESOURCE_CLEANING_UP";
	var JOB_STATE_RUNNING = "JOB_STATE_RUNNING";
	var JOB_STATE_STOPPED = "JOB_STATE_STOPPED";
	var JOB_STATE_UNKNOWN = "JOB_STATE_UNKNOWN";
	var JOB_STATE_UPDATED = "JOB_STATE_UPDATED";
}