package grest.dataflow.v1b3.types;
@:enum abstract JobMessage_messageImportance(String) from String to String to tink.Stringly {
	var JOB_MESSAGE_BASIC = "JOB_MESSAGE_BASIC";
	var JOB_MESSAGE_DEBUG = "JOB_MESSAGE_DEBUG";
	var JOB_MESSAGE_DETAILED = "JOB_MESSAGE_DETAILED";
	var JOB_MESSAGE_ERROR = "JOB_MESSAGE_ERROR";
	var JOB_MESSAGE_IMPORTANCE_UNKNOWN = "JOB_MESSAGE_IMPORTANCE_UNKNOWN";
	var JOB_MESSAGE_WARNING = "JOB_MESSAGE_WARNING";
}