package grest.dataflow.v1b3.types;
@:enum abstract WorkItemDetails_state(String) from String to String to tink.Stringly {
	var EXECUTION_STATE_CANCELLED = "EXECUTION_STATE_CANCELLED";
	var EXECUTION_STATE_FAILED = "EXECUTION_STATE_FAILED";
	var EXECUTION_STATE_NOT_STARTED = "EXECUTION_STATE_NOT_STARTED";
	var EXECUTION_STATE_RUNNING = "EXECUTION_STATE_RUNNING";
	var EXECUTION_STATE_SUCCEEDED = "EXECUTION_STATE_SUCCEEDED";
	var EXECUTION_STATE_UNKNOWN = "EXECUTION_STATE_UNKNOWN";
}