package grest.deploymentmanager.v2.types;
typedef Deployment = {
	/**
		An optional user-provided description of the deployment.
	**/
	@:optional
	var description : String;
	/**
		Provides a fingerprint to use in requests to modify a deployment, such as `update()`, `stop()`, and `cancelPreview()` requests. A fingerprint is a randomly generated value that must be provided with `update()`, `stop()`, and `cancelPreview()` requests to perform optimistic locking. This ensures optimistic concurrency so that only one request happens at a time. The fingerprint is initially generated by Deployment Manager and changes after every request to modify data. To get the latest fingerprint value, perform a `get()` request to a deployment.
	**/
	@:optional
	var fingerprint : String;
	@:optional
	var id : String;
	/**
		Output only. Creation timestamp in RFC3339 text format.
	**/
	@:optional
	var insertTime : String;
	/**
		Map of One Platform labels; provided by the client when the resource is created or updated. Specifically: Label keys must be between 1 and 63 characters long and must conform to the following regular expression: `[a-z]([-a-z0-9]*[a-z0-9])?` Label values must be between 0 and 63 characters long and must conform to the regular expression `([a-z]([-a-z0-9]*[a-z0-9])?)?`.
	**/
	@:optional
	var labels : Array<DeploymentLabelEntry>;
	/**
		Output only. URL of the manifest representing the last manifest that was successfully deployed. If no manifest has been successfully deployed, this field will be absent.
	**/
	@:optional
	var manifest : String;
	/**
		Name of the resource; provided by the client when the resource is created. The name must be 1-63 characters long, and comply with RFC1035. Specifically, the name must be 1-63 characters long and match the regular expression `[a-z]([-a-z0-9]*[a-z0-9])?` which means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or digit, except the last character, which cannot be a dash.
	**/
	@:optional
	var name : String;
	/**
		Output only. The Operation that most recently ran, or is currently running, on this deployment.
	**/
	@:optional
	var operation : Operation;
	/**
		Output only. Server defined URL for the resource.
	**/
	@:optional
	var selfLink : String;
	/**
		[Input Only] The parameters that define your deployment, including the deployment configuration and relevant templates.
	**/
	@:optional
	var target : TargetConfiguration;
	/**
		Output only. If Deployment Manager is currently updating or previewing an update to this deployment, the updated configuration appears here.
	**/
	@:optional
	var update : DeploymentUpdate;
	/**
		Output only. Update timestamp in RFC3339 text format.
	**/
	@:optional
	var updateTime : String;
}