package grest.realtimebidding.v1.types;
@:enum abstract MediaFile_mimeType(String) from String to String to tink.Stringly {
	var MIME_APPLICATION_JAVASCRIPT = "MIME_APPLICATION_JAVASCRIPT";
	var MIME_APPLICATION_MPEGDASH = "MIME_APPLICATION_MPEGDASH";
	var MIME_APPLICATION_MPEGURL = "MIME_APPLICATION_MPEGURL";
	var MIME_APPLICATION_SILVERLIGHT = "MIME_APPLICATION_SILVERLIGHT";
	var MIME_APPLICATION_SURVEY = "MIME_APPLICATION_SURVEY";
	var MIME_APPLICATION_SWF = "MIME_APPLICATION_SWF";
	var MIME_AUDIO_MP3 = "MIME_AUDIO_MP3";
	var MIME_AUDIO_MP4A = "MIME_AUDIO_MP4A";
	var MIME_AUDIO_OGG = "MIME_AUDIO_OGG";
	var MIME_VIDEO_3GPP = "MIME_VIDEO_3GPP";
	var MIME_VIDEO_MOV = "MIME_VIDEO_MOV";
	var MIME_VIDEO_MP4 = "MIME_VIDEO_MP4";
	var MIME_VIDEO_OGG = "MIME_VIDEO_OGG";
	var MIME_VIDEO_WEBM = "MIME_VIDEO_WEBM";
	var MIME_VIDEO_XFLV = "MIME_VIDEO_XFLV";
	var MIME_VIDEO_X_MS_WMV = "MIME_VIDEO_X_MS_WMV";
	var MIME_VIDEO_YT_HOSTED = "MIME_VIDEO_YT_HOSTED";
	var VIDEO_MIME_TYPE_UNSPECIFIED = "VIDEO_MIME_TYPE_UNSPECIFIED";
}