package grest.paymentsresellersubscription.v1.types;
@:enum abstract GoogleCloudPaymentsResellerSubscriptionV1CancelSubscriptionRequest_cancellationReason(String) from String to String to tink.Stringly {
	var CANCELLATION_REASON_ACCIDENTAL_PURCHASE = "CANCELLATION_REASON_ACCIDENTAL_PURCHASE";
	var CANCELLATION_REASON_ACCOUNT_CLOSED = "CANCELLATION_REASON_ACCOUNT_CLOSED";
	var CANCELLATION_REASON_FRAUD = "CANCELLATION_REASON_FRAUD";
	var CANCELLATION_REASON_OTHER = "CANCELLATION_REASON_OTHER";
	var CANCELLATION_REASON_PAST_DUE = "CANCELLATION_REASON_PAST_DUE";
	var CANCELLATION_REASON_REMORSE = "CANCELLATION_REASON_REMORSE";
	var CANCELLATION_REASON_UNSPECIFIED = "CANCELLATION_REASON_UNSPECIFIED";
	var CANCELLATION_REASON_UPGRADE_DOWNGRADE = "CANCELLATION_REASON_UPGRADE_DOWNGRADE";
}