package grest.firebaserules.v1.types;
typedef Ruleset = {
	/**
		Time the `Ruleset` was created. Output only.
	**/
	@:optional
	var createTime : String;
	/**
		The metadata for this ruleset. Output only.
	**/
	@:optional
	var metadata : Metadata;
	/**
		Name of the `Ruleset`. The ruleset_id is auto generated by the service. Format: `projects/{project_id}/rulesets/{ruleset_id}` Output only.
	**/
	@:optional
	var name : String;
	/**
		`Source` for the `Ruleset`.
	**/
	@:optional
	var source : Source;
}