package grest.people.v1.types;
@:enum abstract MiscKeyword_type(String) from String to String to tink.Stringly {
	var HOME = "HOME";
	var OTHER = "OTHER";
	var OUTLOOK_BILLING_INFORMATION = "OUTLOOK_BILLING_INFORMATION";
	var OUTLOOK_DIRECTORY_SERVER = "OUTLOOK_DIRECTORY_SERVER";
	var OUTLOOK_KEYWORD = "OUTLOOK_KEYWORD";
	var OUTLOOK_MILEAGE = "OUTLOOK_MILEAGE";
	var OUTLOOK_PRIORITY = "OUTLOOK_PRIORITY";
	var OUTLOOK_SENSITIVITY = "OUTLOOK_SENSITIVITY";
	var OUTLOOK_SUBJECT = "OUTLOOK_SUBJECT";
	var OUTLOOK_USER = "OUTLOOK_USER";
	var TYPE_UNSPECIFIED = "TYPE_UNSPECIFIED";
	var WORK = "WORK";
}