package grest.people.v1.types;
typedef Source = {
	/**
		**Only populated in `person.metadata.sources`.** The [HTTP entity tag](https://en.wikipedia.org/wiki/HTTP_ETag) of the source. Used for web cache validation.
	**/
	@:optional
	var etag : String;
	/**
		The unique identifier within the source type generated by the server.
	**/
	@:optional
	var id : String;
	/**
		Output only. **Only populated in `person.metadata.sources`.** Metadata about a source of type PROFILE.
	**/
	@:optional
	var profileMetadata : ProfileMetadata;
	/**
		The source type.
	**/
	@:optional
	var type : grest.people.v1.types.Source_type;
	/**
		Output only. **Only populated in `person.metadata.sources`.** Last update timestamp of this source.
	**/
	@:optional
	var updateTime : String;
}