package grest.jobs.v4.types;
typedef ClientEvent = {
	/**
		Required. The timestamp of the event.
	**/
	@:optional
	var createTime : String;
	/**
		Required. A unique identifier, generated by the client application.
	**/
	@:optional
	var eventId : String;
	/**
		Notes about the event provided by recruiters or other users, for example, feedback on why a job was bookmarked.
	**/
	@:optional
	var eventNotes : String;
	/**
		An event issued when a job seeker interacts with the application that implements Cloud Talent Solution.
	**/
	@:optional
	var jobEvent : JobEvent;
	/**
		Strongly recommended for the best service experience. A unique ID generated in the API responses. It can be found in ResponseMetadata.request_id.
	**/
	@:optional
	var requestId : String;
}