package grest.jobs.v4.types;
typedef Company = {
	/**
		The URI to employer's career site or careers page on the employer's web site, for example, "https://careers.google.com".
	**/
	@:optional
	var careerSiteUri : String;
	/**
		Output only. Derived details about the company.
	**/
	@:optional
	var derivedInfo : CompanyDerivedInfo;
	/**
		Required. The display name of the company, for example, "Google LLC".
	**/
	@:optional
	var displayName : String;
	/**
		Equal Employment Opportunity legal disclaimer text to be associated with all jobs, and typically to be displayed in all roles. The maximum number of allowed characters is 500.
	**/
	@:optional
	var eeoText : String;
	/**
		Required. Client side company identifier, used to uniquely identify the company. The maximum number of allowed characters is 255.
	**/
	@:optional
	var externalId : String;
	/**
		The street address of the company's main headquarters, which may be different from the job location. The service attempts to geolocate the provided address, and populates a more specific location wherever possible in DerivedInfo.headquarters_location.
	**/
	@:optional
	var headquartersAddress : String;
	/**
		Set to true if it is the hiring agency that post jobs for other employers. Defaults to false if not provided.
	**/
	@:optional
	var hiringAgency : Bool;
	/**
		A URI that hosts the employer's company logo.
	**/
	@:optional
	var imageUri : String;
	/**
		A list of keys of filterable Job.custom_attributes, whose corresponding `string_values` are used in keyword searches. Jobs with `string_values` under these specified field keys are returned if any of the values match the search keyword. Custom field values with parenthesis, brackets and special symbols are not searchable as-is, and those keyword queries must be surrounded by quotes.
	**/
	@:optional
	var keywordSearchableJobCustomAttributes : Array<String>;
	/**
		Required during company update. The resource name for a company. This is generated by the service when a company is created. The format is "projects/{project_id}/tenants/{tenant_id}/companies/{company_id}", for example, "projects/foo/tenants/bar/companies/baz".
	**/
	@:optional
	var name : String;
	/**
		The employer's company size.
	**/
	@:optional
	var size : grest.jobs.v4.types.Company_size;
	/**
		Output only. Indicates whether a company is flagged to be suspended from public availability by the service when job content appears suspicious, abusive, or spammy.
	**/
	@:optional
	var suspended : Bool;
	/**
		The URI representing the company's primary web site or home page, for example, "https://www.google.com". The maximum number of allowed characters is 255.
	**/
	@:optional
	var websiteUri : String;
}