package grest.jobs.v4.types;
@:enum abstract JobEvent_type(String) from String to String to tink.Stringly {
	var APPLICATION_COMPANY_SUBMIT = "APPLICATION_COMPANY_SUBMIT";
	var APPLICATION_FINISH = "APPLICATION_FINISH";
	var APPLICATION_QUICK_SUBMISSION = "APPLICATION_QUICK_SUBMISSION";
	var APPLICATION_REDIRECT = "APPLICATION_REDIRECT";
	var APPLICATION_REDIRECT_FROM_SEARCH = "APPLICATION_REDIRECT_FROM_SEARCH";
	var APPLICATION_START = "APPLICATION_START";
	var APPLICATION_START_FROM_SEARCH = "APPLICATION_START_FROM_SEARCH";
	var BOOKMARK = "BOOKMARK";
	var HIRED = "HIRED";
	var IMPRESSION = "IMPRESSION";
	var INTERVIEW_GRANTED = "INTERVIEW_GRANTED";
	var JOB_EVENT_TYPE_UNSPECIFIED = "JOB_EVENT_TYPE_UNSPECIFIED";
	var NOTIFICATION = "NOTIFICATION";
	var SENT_CV = "SENT_CV";
	var VIEW = "VIEW";
	var VIEW_REDIRECT = "VIEW_REDIRECT";
}