package grest.jobs.v4.types;
@:enum abstract Location_locationType(String) from String to String to tink.Stringly {
	var ADMINISTRATIVE_AREA = "ADMINISTRATIVE_AREA";
	var COUNTRY = "COUNTRY";
	var LOCALITY = "LOCALITY";
	var LOCATION_TYPE_UNSPECIFIED = "LOCATION_TYPE_UNSPECIFIED";
	var NEIGHBORHOOD = "NEIGHBORHOOD";
	var POSTAL_CODE = "POSTAL_CODE";
	var STREET_ADDRESS = "STREET_ADDRESS";
	var SUB_ADMINISTRATIVE_AREA = "SUB_ADMINISTRATIVE_AREA";
	var SUB_LOCALITY = "SUB_LOCALITY";
	var SUB_LOCALITY_1 = "SUB_LOCALITY_1";
	var SUB_LOCALITY_2 = "SUB_LOCALITY_2";
}