package grest.content.v2.1.types;
@:enum abstract InapplicabilityDetails_inapplicableReason(String) from String to String to tink.Stringly {
	var ALREADY_WINNING_BUYBOX = "ALREADY_WINNING_BUYBOX";
	var CANNOT_BEAT_BUYBOX_WINNER = "CANNOT_BEAT_BUYBOX_WINNER";
	var INAPPLICABLE_REASON_UNSPECIFIED = "INAPPLICABLE_REASON_UNSPECIFIED";
	var INVALID_AUTO_PRICE_MIN = "INVALID_AUTO_PRICE_MIN";
	var INVALID_FLOOR_CONFIG = "INVALID_FLOOR_CONFIG";
	var RESTRICTIONS_NOT_MET = "RESTRICTIONS_NOT_MET";
	var TRIUMPHED_OVER_BY_OTHER_RULE_ON_OFFER = "TRIUMPHED_OVER_BY_OTHER_RULE_ON_OFFER";
	var TRIUMPHED_OVER_BY_SAME_TYPE_RULE = "TRIUMPHED_OVER_BY_SAME_TYPE_RULE";
	var UNCATEGORIZED = "UNCATEGORIZED";
}