package grest.content.v2.1.types;
typedef MerchantOrderReturn = {
	/**
		The date of creation of the return, in ISO 8601 format.
	**/
	@:optional
	var creationDate : String;
	/**
		Merchant defined order ID.
	**/
	@:optional
	var merchantOrderId : String;
	/**
		Google order ID.
	**/
	@:optional
	var orderId : String;
	/**
		Order return ID generated by Google.
	**/
	@:optional
	var orderReturnId : String;
	/**
		Items of the return.
	**/
	@:optional
	var returnItems : Array<MerchantOrderReturnItem>;
	/**
		Information about shipping costs.
	**/
	@:optional
	var returnPricingInfo : ReturnPricingInfo;
	/**
		Shipments of the return.
	**/
	@:optional
	var returnShipments : Array<ReturnShipment>;
}