package grest.content.v2.1.types;
@:enum abstract RepricingRuleEligibleOfferMatcher_matcherOption(String) from String to String to tink.Stringly {
	var MATCHER_OPTION_ALL_PRODUCTS = "MATCHER_OPTION_ALL_PRODUCTS";
	var MATCHER_OPTION_CUSTOM_FILTER = "MATCHER_OPTION_CUSTOM_FILTER";
	var MATCHER_OPTION_UNSPECIFIED = "MATCHER_OPTION_UNSPECIFIED";
	var MATCHER_OPTION_USE_FEED_ATTRIBUTE = "MATCHER_OPTION_USE_FEED_ATTRIBUTE";
}