package grest.content.v2.1.types;
typedef RepricingRuleReport = {
	/**
		Stats specific to buybox winning rules for rule report (deprecated).
	**/
	@:optional
	var buyboxWinningRuleStats : RepricingRuleReportBuyboxWinningRuleStats;
	/**
		Date of the stats in this report. The report starts and ends according to the merchant's timezone.
	**/
	@:optional
	var date : Date;
	/**
		List of product ids that are impacted by this rule during this reporting period. Out of stock products and products not searched for by customers are examples of non-impacted products.
	**/
	@:optional
	var impactedProducts : Array<String>;
	/**
		List of all reasons the rule did not apply to the inapplicable products during the specified reporting period.
	**/
	@:optional
	var inapplicabilityDetails : Array<InapplicabilityDetails>;
	/**
		List of product ids that are inapplicable to this rule during this reporting period. To get the inapplicable reason for a specific product, see RepricingProductReport.
	**/
	@:optional
	var inapplicableProducts : Array<String>;
	/**
		Total unit count of impacted products ordered while the rule was active on the date of the report. This count includes all orders that were started while the rule was active, even if the rule was no longer active when the order was completed.
	**/
	@:optional
	var orderItemCount : Int;
	/**
		Id of the Repricing rule for this report.
	**/
	@:optional
	var ruleId : String;
	/**
		Total GMV generated by impacted products while the rule was active on the date of the report. This value includes all orders that were started while the rule was active, even if the rule was no longer active when the order was completed.
	**/
	@:optional
	var totalGmv : PriceAmount;
	/**
		Type of the rule.
	**/
	@:optional
	var type : grest.content.v2.1.types.RepricingRuleReport_type;
}