package grest.content.v2.1.types;
typedef ReturnPolicyOnline = {
	/**
		The countries of sale where the return policy is applicable. The values must be a valid 2 letter ISO 3166 code, e.g. "US".
	**/
	@:optional
	var countries : Array<String>;
	/**
		The item conditions that are accepted for returns. This is required to not be empty unless the type of return policy is noReturns.
	**/
	@:optional
	var itemConditions : Array<String>;
	/**
		The unique user-defined label of the return policy. The same label cannot be used in different return policies for the same country. Policies with the label 'default' will apply to all products, unless a product specifies a return_policy_label attribute.
	**/
	@:optional
	var label : String;
	/**
		The name of the policy as shown in Merchant Center.
	**/
	@:optional
	var name : String;
	/**
		The return policy.
	**/
	@:optional
	var policy : ReturnPolicyOnlinePolicy;
	/**
		The restocking fee that applies to all return reason categories. This would be treated as a free restocking fee if the value is not set.
	**/
	@:optional
	var restockingFee : ReturnPolicyOnlineRestockingFee;
	/**
		The return methods of how customers can return an item. This value is required to not be empty unless the type of return policy is noReturns.
	**/
	@:optional
	var returnMethods : Array<String>;
	/**
		Output only. Return policy ID generated by Google.
	**/
	@:optional
	var returnPolicyId : String;
	/**
		The return policy uri. This can used by Google to do a sanity check for the policy.
	**/
	@:optional
	var returnPolicyUri : String;
	/**
		The return reason category information. This required to not be empty unless the type of return policy is noReturns.
	**/
	@:optional
	var returnReasonCategoryInfo : Array<ReturnPolicyOnlineReturnReasonCategoryInfo>;
}