package grest.content.v2.1.types;
typedef ReturnAddress = {
	/**
		Required. The address.
	**/
	@:optional
	var address : ReturnAddressAddress;
	/**
		Required. The country of sale where the return address is applicable.
	**/
	@:optional
	var country : String;
	/**
		Identifies what kind of resource this is. Value: the fixed string "`content#returnAddress`"
	**/
	@:optional
	var kind : String;
	/**
		Required. The user-defined label of the return address. For the default address, use the label "default".
	**/
	@:optional
	var label : String;
	/**
		Required. The merchant's contact phone number regarding the return.
	**/
	@:optional
	var phoneNumber : String;
	/**
		Return address ID generated by Google.
	**/
	@:optional
	var returnAddressId : String;
}