package grest.videointelligence.v1.types;
@:enum abstract GoogleCloudVideointelligenceV1_VideoAnnotationProgress_feature(String) from String to String to tink.Stringly {
	var EXPLICIT_CONTENT_DETECTION = "EXPLICIT_CONTENT_DETECTION";
	var FACE_DETECTION = "FACE_DETECTION";
	var FEATURE_UNSPECIFIED = "FEATURE_UNSPECIFIED";
	var LABEL_DETECTION = "LABEL_DETECTION";
	var LOGO_RECOGNITION = "LOGO_RECOGNITION";
	var OBJECT_TRACKING = "OBJECT_TRACKING";
	var PERSON_DETECTION = "PERSON_DETECTION";
	var SHOT_CHANGE_DETECTION = "SHOT_CHANGE_DETECTION";
	var SPEECH_TRANSCRIPTION = "SPEECH_TRANSCRIPTION";
	var TEXT_DETECTION = "TEXT_DETECTION";
}