package grest.doubleclickbidmanager.v1.1.types;
@:enum abstract QueryMetadata_dataRange(String) from String to String to tink.Stringly {
	var ALL_TIME = "ALL_TIME";
	var CURRENT_DAY = "CURRENT_DAY";
	var CUSTOM_DATES = "CUSTOM_DATES";
	var LAST_14_DAYS = "LAST_14_DAYS";
	var LAST_30_DAYS = "LAST_30_DAYS";
	var LAST_365_DAYS = "LAST_365_DAYS";
	var LAST_60_DAYS = "LAST_60_DAYS";
	var LAST_7_DAYS = "LAST_7_DAYS";
	var LAST_90_DAYS = "LAST_90_DAYS";
	var MONTH_TO_DATE = "MONTH_TO_DATE";
	var PREVIOUS_DAY = "PREVIOUS_DAY";
	var PREVIOUS_HALF_MONTH = "PREVIOUS_HALF_MONTH";
	var PREVIOUS_MONTH = "PREVIOUS_MONTH";
	var PREVIOUS_QUARTER = "PREVIOUS_QUARTER";
	var PREVIOUS_WEEK = "PREVIOUS_WEEK";
	var PREVIOUS_YEAR = "PREVIOUS_YEAR";
	var QUARTER_TO_DATE = "QUARTER_TO_DATE";
	var TYPE_NOT_SUPPORTED = "TYPE_NOT_SUPPORTED";
	var WEEK_TO_DATE = "WEEK_TO_DATE";
	var YEAR_TO_DATE = "YEAR_TO_DATE";
}