package grest.doubleclickbidmanager.v1.1.types;
@:enum abstract ReportFailure_errorCode(String) from String to String to tink.Stringly {
	var AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
	var DEPRECATED_REPORTING_INVALID_QUERY = "DEPRECATED_REPORTING_INVALID_QUERY";
	var REPORTING_BUCKET_NOT_FOUND = "REPORTING_BUCKET_NOT_FOUND";
	var REPORTING_CREATE_BUCKET_FAILED = "REPORTING_CREATE_BUCKET_FAILED";
	var REPORTING_DELETE_BUCKET_FAILED = "REPORTING_DELETE_BUCKET_FAILED";
	var REPORTING_FATAL_ERROR = "REPORTING_FATAL_ERROR";
	var REPORTING_ILLEGAL_FILENAME = "REPORTING_ILLEGAL_FILENAME";
	var REPORTING_IMCOMPATIBLE_METRICS = "REPORTING_IMCOMPATIBLE_METRICS";
	var REPORTING_INVALID_QUERY_MISSING_PARTNER_AND_ADVERTISER_FILTERS = "REPORTING_INVALID_QUERY_MISSING_PARTNER_AND_ADVERTISER_FILTERS";
	var REPORTING_INVALID_QUERY_TITLE_MISSING = "REPORTING_INVALID_QUERY_TITLE_MISSING";
	var REPORTING_INVALID_QUERY_TOO_MANY_UNFILTERED_LARGE_GROUP_BYS = "REPORTING_INVALID_QUERY_TOO_MANY_UNFILTERED_LARGE_GROUP_BYS";
	var REPORTING_QUERY_NOT_FOUND = "REPORTING_QUERY_NOT_FOUND";
	var REPORTING_TRANSIENT_ERROR = "REPORTING_TRANSIENT_ERROR";
	var REPORTING_UPDATE_BUCKET_PERMISSION_FAILED = "REPORTING_UPDATE_BUCKET_PERMISSION_FAILED";
	var REPORTING_WRITE_BUCKET_OBJECT_FAILED = "REPORTING_WRITE_BUCKET_OBJECT_FAILED";
	var SERVER_ERROR = "SERVER_ERROR";
	var UNAUTHORIZED_API_ACCESS = "UNAUTHORIZED_API_ACCESS";
	var VALIDATION_ERROR = "VALIDATION_ERROR";
}