package grest.doubleclicksearch.v2.types;
typedef Report = {
	/**
		Asynchronous report only. Contains a list of generated report files once the report has successfully completed.
	**/
	@:optional
	var files : Array<{ var byteCount : String; var url : String; }>;
	/**
		Asynchronous report only. Id of the report.
	**/
	@:optional
	var id : String;
	/**
		Asynchronous report only. True if and only if the report has completed successfully and the report files are ready to be downloaded.
	**/
	@:optional
	var isReportReady : Bool;
	/**
		Identifies this as a Report resource. Value: the fixed string `doubleclicksearch#report`.
	**/
	@:optional
	var kind : String;
	/**
		The request that created the report. Optional fields not specified in the original request are filled with default values.
	**/
	@:optional
	var request : ReportRequest;
	/**
		The number of report rows generated by the report, not including headers.
	**/
	@:optional
	var rowCount : Int;
	/**
		Synchronous report only. Generated report rows.
	**/
	@:optional
	var rows : Array<ReportRow>;
	/**
		The currency code of all monetary values produced in the report, including values that are set by users (e.g., keyword bid settings) and metrics (e.g., cost and revenue). The currency code of a report is determined by the `statisticsCurrency` field of the report request.
	**/
	@:optional
	var statisticsCurrencyCode : String;
	/**
		If all statistics of the report are sourced from the same time zone, this would be it. Otherwise the field is unset.
	**/
	@:optional
	var statisticsTimeZone : String;
}