package grest.sqladmin.v1beta4.types;
typedef InsightsConfig = {
	/**
		Whether Query Insights feature is enabled.
	**/
	@:optional
	var queryInsightsEnabled : Bool;
	/**
		Number of query plans generated by Insights per minute. Default is 5. Changing this will restart the database.
	**/
	@:optional
	var queryPlansPerMinute : Int;
	/**
		Maximum query length stored in bytes. Default value: 1024 bytes. Range: 256-4500 bytes. Query length more than this field value will be truncated to this value. When unset, query length will be the default value. Changing query length will restart the database.
	**/
	@:optional
	var queryStringLength : Int;
	/**
		Whether Query Insights will record application tags from query when enabled.
	**/
	@:optional
	var recordApplicationTags : Bool;
	/**
		Whether Query Insights will record client address when enabled.
	**/
	@:optional
	var recordClientAddress : Bool;
}