package grest.sqladmin.v1beta4.types;
@:enum abstract SqlExternalSyncSettingError_type(String) from String to String to tink.Stringly {
	var BINLOG_NOT_ENABLED = "BINLOG_NOT_ENABLED";
	var CONNECTION_FAILURE = "CONNECTION_FAILURE";
	var INCOMPATIBLE_DATABASE_VERSION = "INCOMPATIBLE_DATABASE_VERSION";
	var INSUFFICIENT_MAX_REPLICATION_SLOTS = "INSUFFICIENT_MAX_REPLICATION_SLOTS";
	var INSUFFICIENT_MAX_WAL_SENDERS = "INSUFFICIENT_MAX_WAL_SENDERS";
	var INSUFFICIENT_MAX_WORKER_PROCESSES = "INSUFFICIENT_MAX_WORKER_PROCESSES";
	var INSUFFICIENT_PRIVILEGE = "INSUFFICIENT_PRIVILEGE";
	var INVALID_DB_PARAM = "INVALID_DB_PARAM";
	var INVALID_LOGGING_SETUP = "INVALID_LOGGING_SETUP";
	var INVALID_RDS_LOGICAL_REPLICATION = "INVALID_RDS_LOGICAL_REPLICATION";
	var INVALID_SHARED_PRELOAD_LIBRARY = "INVALID_SHARED_PRELOAD_LIBRARY";
	var INVALID_WAL_LEVEL = "INVALID_WAL_LEVEL";
	var NO_PGLOGICAL_INSTALLED = "NO_PGLOGICAL_INSTALLED";
	var PGLOGICAL_NODE_ALREADY_EXISTS = "PGLOGICAL_NODE_ALREADY_EXISTS";
	var PRIMARY_ALREADY_SETUP = "PRIMARY_ALREADY_SETUP";
	var REPLICA_ALREADY_SETUP = "REPLICA_ALREADY_SETUP";
	var SQLSERVER_AGENT_NOT_RUNNING = "SQLSERVER_AGENT_NOT_RUNNING";
	var SQLSERVER_SERVERNAME_MISMATCH = "SQLSERVER_SERVERNAME_MISMATCH";
	var SQL_EXTERNAL_SYNC_SETTING_ERROR_TYPE_UNSPECIFIED = "SQL_EXTERNAL_SYNC_SETTING_ERROR_TYPE_UNSPECIFIED";
	var UNSUPPORTED_DEFINER = "UNSUPPORTED_DEFINER";
	var UNSUPPORTED_EXTENSIONS = "UNSUPPORTED_EXTENSIONS";
	var UNSUPPORTED_GTID_MODE = "UNSUPPORTED_GTID_MODE";
	var UNSUPPORTED_MIGRATION_TYPE = "UNSUPPORTED_MIGRATION_TYPE";
	var UNSUPPORTED_TABLE_DEFINITION = "UNSUPPORTED_TABLE_DEFINITION";
}