package grest.sqladmin.v1beta4.types;
typedef SqlOutOfDiskReport = {
	/**
		The minimum recommended increase size in GigaBytes This field is consumed by the frontend Writers: -- the proactive database wellness job for OOD.
	**/
	@:optional
	var sqlMinRecommendedIncreaseSizeGb : Int;
	/**
		This field represents the state generated by the proactive database wellness job for OutOfDisk issues. Writers: -- the proactive database wellness job for OOD. Readers: -- the proactive database wellness job
	**/
	@:optional
	var sqlOutOfDiskState : grest.sqladmin.v1beta4.types.SqlOutOfDiskReport_sqlOutOfDiskState;
}