package grest.sqladmin.v1beta4.types;
typedef SslCertsInsertResponse = {
	/**
		The new client certificate and private key.
	**/
	@:optional
	var clientCert : SslCertDetail;
	/**
		This is always *sql#sslCertsInsert*.
	**/
	@:optional
	var kind : String;
	/**
		The operation to track the ssl certs insert request.
	**/
	@:optional
	var operation : Operation;
	/**
		The server Certificate Authority's certificate. If this is missing you can force a new one to be generated by calling resetSslConfig method on instances resource.
	**/
	@:optional
	var serverCaCert : SslCert;
}