package grest.safebrowsing.v4.types;
@:enum abstract GoogleSecuritySafebrowsingV4FetchThreatListUpdatesResponseListUpdateResponse_threatType(String) from String to String to tink.Stringly {
	var ACCURACY_TIPS = "ACCURACY_TIPS";
	var API_ABUSE = "API_ABUSE";
	var APK_MALWARE_OFFLINE = "APK_MALWARE_OFFLINE";
	var CLIENT_INCIDENT = "CLIENT_INCIDENT";
	var CLIENT_INCIDENT_WHITELIST = "CLIENT_INCIDENT_WHITELIST";
	var CSD_DOWNLOAD_WHITELIST = "CSD_DOWNLOAD_WHITELIST";
	var CSD_WHITELIST = "CSD_WHITELIST";
	var HIGH_CONFIDENCE_ALLOWLIST = "HIGH_CONFIDENCE_ALLOWLIST";
	var MALICIOUS_BINARY = "MALICIOUS_BINARY";
	var MALWARE = "MALWARE";
	var POTENTIALLY_HARMFUL_APPLICATION = "POTENTIALLY_HARMFUL_APPLICATION";
	var SOCIAL_ENGINEERING = "SOCIAL_ENGINEERING";
	var SOCIAL_ENGINEERING_INTERNAL = "SOCIAL_ENGINEERING_INTERNAL";
	var SUBRESOURCE_FILTER = "SUBRESOURCE_FILTER";
	var SUSPICIOUS = "SUSPICIOUS";
	var THREAT_TYPE_UNSPECIFIED = "THREAT_TYPE_UNSPECIFIED";
	var TRICK_TO_BILL = "TRICK_TO_BILL";
	var UNWANTED_SOFTWARE = "UNWANTED_SOFTWARE";
}