package grest.adexchangebuyer2.v2beta1.types;
@:enum abstract Correction_type(String) from String to String to tink.Stringly {
	var CORRECTION_TYPE_UNSPECIFIED = "CORRECTION_TYPE_UNSPECIFIED";
	var FLASH_ATTRIBUTE_REMOVED = "FLASH_ATTRIBUTE_REMOVED";
	var FLASH_FREE_ATTRIBUTE_ADDED = "FLASH_FREE_ATTRIBUTE_ADDED";
	var FLASH_FREE_ATTRIBUTE_REMOVED = "FLASH_FREE_ATTRIBUTE_REMOVED";
	var IN_BANNER_VIDEO_ATTRIBUTE_ADDED = "IN_BANNER_VIDEO_ATTRIBUTE_ADDED";
	var MRAID_ATTRIBUTE_ADDED = "MRAID_ATTRIBUTE_ADDED";
	var REQUIRED_ATTRIBUTE_ADDED = "REQUIRED_ATTRIBUTE_ADDED";
	var REQUIRED_VENDOR_ADDED = "REQUIRED_VENDOR_ADDED";
	var SSL_ATTRIBUTE_ADDED = "SSL_ATTRIBUTE_ADDED";
	var SSL_ATTRIBUTE_REMOVED = "SSL_ATTRIBUTE_REMOVED";
	var VENDOR_IDS_ADDED = "VENDOR_IDS_ADDED";
	var VIDEO_IN_SNIPPET_ATTRIBUTE_ADDED = "VIDEO_IN_SNIPPET_ATTRIBUTE_ADDED";
}