package grest.cloudchannel.v1.types;
@:enum abstract GoogleCloudChannelV1OperationMetadata_operationType(String) from String to String to tink.Stringly {
	var ACTIVATE_ENTITLEMENT = "ACTIVATE_ENTITLEMENT";
	var CANCEL_ENTITLEMENT = "CANCEL_ENTITLEMENT";
	var CHANGE_OFFER = "CHANGE_OFFER";
	var CHANGE_PARAMETERS = "CHANGE_PARAMETERS";
	var CHANGE_RENEWAL_SETTINGS = "CHANGE_RENEWAL_SETTINGS";
	var CREATE_ENTITLEMENT = "CREATE_ENTITLEMENT";
	var OPERATION_TYPE_UNSPECIFIED = "OPERATION_TYPE_UNSPECIFIED";
	var PROVISION_CLOUD_IDENTITY = "PROVISION_CLOUD_IDENTITY";
	var START_PAID_SERVICE = "START_PAID_SERVICE";
	var SUSPEND_ENTITLEMENT = "SUSPEND_ENTITLEMENT";
	var TRANSFER_ENTITLEMENTS = "TRANSFER_ENTITLEMENTS";
	var TRANSFER_ENTITLEMENTS_TO_GOOGLE = "TRANSFER_ENTITLEMENTS_TO_GOOGLE";
}