package grest.remotebuildexecution.v2.types;
@:enum abstract GoogleDevtoolsRemotebuildbotCommandEvents_outputLocation(String) from String to String to tink.Stringly {
	var LOCATION_EXEC_ROOT_AND_WORKING_DIR_RELATIVE = "LOCATION_EXEC_ROOT_AND_WORKING_DIR_RELATIVE";
	var LOCATION_EXEC_ROOT_AND_WORKING_DIR_RELATIVE_OUTPUT_OUTSIDE_WORKING_DIR = "LOCATION_EXEC_ROOT_AND_WORKING_DIR_RELATIVE_OUTPUT_OUTSIDE_WORKING_DIR";
	var LOCATION_EXEC_ROOT_RELATIVE = "LOCATION_EXEC_ROOT_RELATIVE";
	var LOCATION_EXEC_ROOT_RELATIVE_OUTPUT_OUTSIDE_WORKING_DIR = "LOCATION_EXEC_ROOT_RELATIVE_OUTPUT_OUTSIDE_WORKING_DIR";
	var LOCATION_NONE = "LOCATION_NONE";
	var LOCATION_UNDEFINED = "LOCATION_UNDEFINED";
	var LOCATION_WORKING_DIR_RELATIVE = "LOCATION_WORKING_DIR_RELATIVE";
}