package grest.docs.v1.types;
@:enum abstract CreateParagraphBulletsRequest_bulletPreset(String) from String to String to tink.Stringly {
	var BULLET_ARROW3D_CIRCLE_SQUARE = "BULLET_ARROW3D_CIRCLE_SQUARE";
	var BULLET_ARROW_DIAMOND_DISC = "BULLET_ARROW_DIAMOND_DISC";
	var BULLET_CHECKBOX = "BULLET_CHECKBOX";
	var BULLET_DIAMONDX_ARROW3D_SQUARE = "BULLET_DIAMONDX_ARROW3D_SQUARE";
	var BULLET_DIAMONDX_HOLLOWDIAMOND_SQUARE = "BULLET_DIAMONDX_HOLLOWDIAMOND_SQUARE";
	var BULLET_DIAMOND_CIRCLE_SQUARE = "BULLET_DIAMOND_CIRCLE_SQUARE";
	var BULLET_DISC_CIRCLE_SQUARE = "BULLET_DISC_CIRCLE_SQUARE";
	var BULLET_GLYPH_PRESET_UNSPECIFIED = "BULLET_GLYPH_PRESET_UNSPECIFIED";
	var BULLET_LEFTTRIANGLE_DIAMOND_DISC = "BULLET_LEFTTRIANGLE_DIAMOND_DISC";
	var BULLET_STAR_CIRCLE_SQUARE = "BULLET_STAR_CIRCLE_SQUARE";
	var NUMBERED_DECIMAL_ALPHA_ROMAN = "NUMBERED_DECIMAL_ALPHA_ROMAN";
	var NUMBERED_DECIMAL_ALPHA_ROMAN_PARENS = "NUMBERED_DECIMAL_ALPHA_ROMAN_PARENS";
	var NUMBERED_DECIMAL_NESTED = "NUMBERED_DECIMAL_NESTED";
	var NUMBERED_UPPERALPHA_ALPHA_ROMAN = "NUMBERED_UPPERALPHA_ALPHA_ROMAN";
	var NUMBERED_UPPERROMAN_UPPERALPHA_DECIMAL = "NUMBERED_UPPERROMAN_UPPERALPHA_DECIMAL";
	var NUMBERED_ZERODECIMAL_ALPHA_ROMAN = "NUMBERED_ZERODECIMAL_ALPHA_ROMAN";
}