package grest.poly.v1.types;
@:enum abstract ObjParseError_code(String) from String to String to tink.Stringly {
	var CODE_UNSPECIFIED = "CODE_UNSPECIFIED";
	var FILE_NOT_FOUND = "FILE_NOT_FOUND";
	var FILE_SUBSTITUTION = "FILE_SUBSTITUTION";
	var INCONSISTENT_VERTEX_REFS = "INCONSISTENT_VERTEX_REFS";
	var INVALID_COMMAND = "INVALID_COMMAND";
	var INVALID_FILE_PATH = "INVALID_FILE_PATH";
	var INVALID_NUMBER = "INVALID_NUMBER";
	var INVALID_SMOOTHING_GROUP = "INVALID_SMOOTHING_GROUP";
	var INVALID_TEXTURE_OPTION = "INVALID_TEXTURE_OPTION";
	var INVALID_VALUE = "INVALID_VALUE";
	var INVALID_VERTEX_REF = "INVALID_VERTEX_REF";
	var LINE_TOO_LONG = "LINE_TOO_LONG";
	var MISSING_FILE_NAME = "MISSING_FILE_NAME";
	var MISSING_GEOMETRIC_VERTEX = "MISSING_GEOMETRIC_VERTEX";
	var MISSING_TOKEN = "MISSING_TOKEN";
	var MISSING_VERTEX_COLORS = "MISSING_VERTEX_COLORS";
	var NO_MATERIAL_DEFINED = "NO_MATERIAL_DEFINED";
	var NUMBER_OUT_OF_RANGE = "NUMBER_OUT_OF_RANGE";
	var TOO_FEW_DIMENSIONS = "TOO_FEW_DIMENSIONS";
	var TOO_FEW_VERTICES = "TOO_FEW_VERTICES";
	var TOO_MANY_DIMENSIONS = "TOO_MANY_DIMENSIONS";
	var TOO_MANY_PROBLEMS = "TOO_MANY_PROBLEMS";
	var UNKNOWN_MATERIAL = "UNKNOWN_MATERIAL";
	var UNSUPPORTED_COMMAND = "UNSUPPORTED_COMMAND";
	var UNUSED_TOKENS = "UNUSED_TOKENS";
	var VERTEX_NOT_FOUND = "VERTEX_NOT_FOUND";
}