package grest.reseller.v1.types;
typedef Customer = {
	/**
		Like the "Customer email" in the reseller tools, this email is the secondary contact used if something happens to the customer's service such as service outage or a security issue. This property is required when creating a new customer and should not use the same domain as `customerDomain`.
	**/
	@:optional
	var alternateEmail : String;
	/**
		The customer's primary domain name string. `customerDomain` is required when creating a new customer. Do not include the `www` prefix in the domain when adding a customer.
	**/
	@:optional
	var customerDomain : String;
	/**
		Whether the customer's primary domain has been verified.
	**/
	@:optional
	var customerDomainVerified : Bool;
	/**
		This property will always be returned in a response as the unique identifier generated by Google. In a request, this property can be either the primary domain or the unique identifier generated by Google.
	**/
	@:optional
	var customerId : String;
	/**
		Identifies the resource as a customer. Value: `reseller#customer`
	**/
	@:optional
	var kind : String;
	/**
		Customer contact phone number. Must start with "+" followed by the country code. The rest of the number can be contiguous numbers or respect the phone local format conventions, but it must be a real phone number and not, for example, "123". This field is silently ignored if invalid.
	**/
	@:optional
	var phoneNumber : String;
	/**
		A customer's address information. Each field has a limit of 255 charcters.
	**/
	@:optional
	var postalAddress : Address;
	/**
		URL to customer's Admin console dashboard. The read-only URL is generated by the API service. This is used if your client application requires the customer to complete a task in the Admin console.
	**/
	@:optional
	var resourceUiUrl : String;
}