package grest.servicenetworking.v1.types;
@:enum abstract ValidateConsumerConfigResponse_validationError(String) from String to String to tink.Stringly {
	var COMPUTE_API_NOT_ENABLED = "COMPUTE_API_NOT_ENABLED";
	var CONSUMER_PROJECT_NOT_SERVICE_PROJECT = "CONSUMER_PROJECT_NOT_SERVICE_PROJECT";
	var HOST_PROJECT_NOT_FOUND = "HOST_PROJECT_NOT_FOUND";
	var NETWORK_NOT_FOUND = "NETWORK_NOT_FOUND";
	var NETWORK_NOT_IN_CONSUMERS_HOST_PROJECT = "NETWORK_NOT_IN_CONSUMERS_HOST_PROJECT";
	var NETWORK_NOT_IN_CONSUMERS_PROJECT = "NETWORK_NOT_IN_CONSUMERS_PROJECT";
	var NETWORK_NOT_PEERED = "NETWORK_NOT_PEERED";
	var NETWORK_PEERING_DELETED = "NETWORK_PEERING_DELETED";
	var RANGES_DELETED_LATER = "RANGES_DELETED_LATER";
	var RANGES_EXHAUSTED = "RANGES_EXHAUSTED";
	var RANGES_NOT_RESERVED = "RANGES_NOT_RESERVED";
	var SERVICE_NETWORKING_NOT_ENABLED = "SERVICE_NETWORKING_NOT_ENABLED";
	var VALIDATION_ERROR_UNSPECIFIED = "VALIDATION_ERROR_UNSPECIFIED";
	var VALIDATION_NOT_REQUESTED = "VALIDATION_NOT_REQUESTED";
}