package grest.displayvideo.v1.api.advertisers;
interface Invoices {
	/**
		Lists invoices posted for an advertiser in a given month. Invoices generated by billing profiles with a "Partner" invoice level are not retrievable through this method.
	**/
	@:get("/v1/advertisers/$advertiserId/invoices")
	function list(advertiserId:String, query:{ /**
		The month to list the invoices for. If not set, the request will retrieve invoices for the previous month. Must be in the format YYYYMM.
	**/
	@:optional
	var issueMonth : String; /**
		Select type of invoice to retrieve for Loi Sapin advertisers. Only applicable to Loi Sapin advertisers. Will be ignored otherwise.
	**/
	@:optional
	var loiSapinInvoiceType : grest.displayvideo.v1.types.Api_Invoices_list_loiSapinInvoiceType; /**
		Requested page size. Must be between `1` and `100`. If unspecified will default to `100`. Returns error code `INVALID_ARGUMENT` if an invalid value is specified.
	**/
	@:optional
	var pageSize : Int; /**
		A token identifying a page of results the server should return. Typically, this is the value of next_page_token returned from the previous call to `ListInvoices` method. If not specified, the first page of results will be returned.
	**/
	@:optional
	var pageToken : String; }):grest.displayvideo.v1.types.ListInvoicesResponse;
	/**
		Retrieves the invoice currency used by an advertiser in a given month.
	**/
	@:get("/v1/advertisers/$advertiserId/invoices:lookupInvoiceCurrency")
	function lookupInvoiceCurrency(advertiserId:String, query:{ /**
		Month for which the currency is needed. If not set, the request will return existing currency settings for the advertiser. Must be in the format YYYYMM.
	**/
	@:optional
	var invoiceMonth : String; }):grest.displayvideo.v1.types.LookupInvoiceCurrencyResponse;
}