package grest.searchconsole.v1.types;
@:enum abstract MobileFriendlyIssue_rule(String) from String to String to tink.Stringly {
	var CONFIGURE_VIEWPORT = "CONFIGURE_VIEWPORT";
	var FIXED_WIDTH_VIEWPORT = "FIXED_WIDTH_VIEWPORT";
	var MOBILE_FRIENDLY_RULE_UNSPECIFIED = "MOBILE_FRIENDLY_RULE_UNSPECIFIED";
	var SIZE_CONTENT_TO_VIEWPORT = "SIZE_CONTENT_TO_VIEWPORT";
	var TAP_TARGETS_TOO_CLOSE = "TAP_TARGETS_TOO_CLOSE";
	var USES_INCOMPATIBLE_PLUGINS = "USES_INCOMPATIBLE_PLUGINS";
	var USE_LEGIBLE_FONT_SIZES = "USE_LEGIBLE_FONT_SIZES";
}