package grest.vault.v1.types;
typedef Matter = {
	/**
		The description of the matter.
	**/
	@:optional
	var description : String;
	/**
		The matter ID which is generated by the server. Should be blank when creating a new matter.
	**/
	@:optional
	var matterId : String;
	/**
		List of users and access to the matter. Currently there is no programmer defined limit on the number of permissions a matter can have.
	**/
	@:optional
	var matterPermissions : Array<MatterPermission>;
	/**
		The name of the matter.
	**/
	@:optional
	var name : String;
	/**
		The state of the matter.
	**/
	@:optional
	var state : grest.vault.v1.types.Matter_state;
}