package grest.analyticsdata.v1beta.types;
@:enum abstract MetricHeader_type(String) from String to String to tink.Stringly {
	var METRIC_TYPE_UNSPECIFIED = "METRIC_TYPE_UNSPECIFIED";
	var TYPE_CURRENCY = "TYPE_CURRENCY";
	var TYPE_FEET = "TYPE_FEET";
	var TYPE_FLOAT = "TYPE_FLOAT";
	var TYPE_HOURS = "TYPE_HOURS";
	var TYPE_INTEGER = "TYPE_INTEGER";
	var TYPE_KILOMETERS = "TYPE_KILOMETERS";
	var TYPE_METERS = "TYPE_METERS";
	var TYPE_MILES = "TYPE_MILES";
	var TYPE_MILLISECONDS = "TYPE_MILLISECONDS";
	var TYPE_MINUTES = "TYPE_MINUTES";
	var TYPE_SECONDS = "TYPE_SECONDS";
	var TYPE_STANDARD = "TYPE_STANDARD";
}