package grest.dfareporting.v3.5.types;
@:enum abstract Account_activeAdsLimitTier(String) from String to String to tink.Stringly {
	var ACTIVE_ADS_TIER_100K = "ACTIVE_ADS_TIER_100K";
	var ACTIVE_ADS_TIER_1M = "ACTIVE_ADS_TIER_1M";
	var ACTIVE_ADS_TIER_200K = "ACTIVE_ADS_TIER_200K";
	var ACTIVE_ADS_TIER_300K = "ACTIVE_ADS_TIER_300K";
	var ACTIVE_ADS_TIER_40K = "ACTIVE_ADS_TIER_40K";
	var ACTIVE_ADS_TIER_500K = "ACTIVE_ADS_TIER_500K";
	var ACTIVE_ADS_TIER_750K = "ACTIVE_ADS_TIER_750K";
	var ACTIVE_ADS_TIER_75K = "ACTIVE_ADS_TIER_75K";
}