package grest.dfareporting.v3.5.types;
@:enum abstract Ad_type(String) from String to String to tink.Stringly {
	var AD_SERVING_BRAND_SAFE_AD = "AD_SERVING_BRAND_SAFE_AD";
	var AD_SERVING_CLICK_TRACKER = "AD_SERVING_CLICK_TRACKER";
	var AD_SERVING_DEFAULT_AD = "AD_SERVING_DEFAULT_AD";
	var AD_SERVING_STANDARD_AD = "AD_SERVING_STANDARD_AD";
	var AD_SERVING_TRACKING = "AD_SERVING_TRACKING";
}