package grest.dfareporting.v3.5.types;
@:enum abstract Api_Creatives_list_types(String) from String to String to tink.Stringly {
	var BRAND_SAFE_DEFAULT_INSTREAM_VIDEO = "BRAND_SAFE_DEFAULT_INSTREAM_VIDEO";
	var CUSTOM_DISPLAY = "CUSTOM_DISPLAY";
	var CUSTOM_DISPLAY_INTERSTITIAL = "CUSTOM_DISPLAY_INTERSTITIAL";
	var DISPLAY = "DISPLAY";
	var DISPLAY_IMAGE_GALLERY = "DISPLAY_IMAGE_GALLERY";
	var DISPLAY_REDIRECT = "DISPLAY_REDIRECT";
	var FLASH_INPAGE = "FLASH_INPAGE";
	var HTML5_BANNER = "HTML5_BANNER";
	var IMAGE = "IMAGE";
	var INSTREAM_AUDIO = "INSTREAM_AUDIO";
	var INSTREAM_VIDEO = "INSTREAM_VIDEO";
	var INSTREAM_VIDEO_REDIRECT = "INSTREAM_VIDEO_REDIRECT";
	var INTERNAL_REDIRECT = "INTERNAL_REDIRECT";
	var INTERSTITIAL_INTERNAL_REDIRECT = "INTERSTITIAL_INTERNAL_REDIRECT";
	var RICH_MEDIA_DISPLAY_BANNER = "RICH_MEDIA_DISPLAY_BANNER";
	var RICH_MEDIA_DISPLAY_EXPANDING = "RICH_MEDIA_DISPLAY_EXPANDING";
	var RICH_MEDIA_DISPLAY_INTERSTITIAL = "RICH_MEDIA_DISPLAY_INTERSTITIAL";
	var RICH_MEDIA_DISPLAY_MULTI_FLOATING_INTERSTITIAL = "RICH_MEDIA_DISPLAY_MULTI_FLOATING_INTERSTITIAL";
	var RICH_MEDIA_IM_EXPAND = "RICH_MEDIA_IM_EXPAND";
	var RICH_MEDIA_INPAGE_FLOATING = "RICH_MEDIA_INPAGE_FLOATING";
	var RICH_MEDIA_MOBILE_IN_APP = "RICH_MEDIA_MOBILE_IN_APP";
	var RICH_MEDIA_PEEL_DOWN = "RICH_MEDIA_PEEL_DOWN";
	var TRACKING_TEXT = "TRACKING_TEXT";
	var VPAID_LINEAR_VIDEO = "VPAID_LINEAR_VIDEO";
	var VPAID_NON_LINEAR_VIDEO = "VPAID_NON_LINEAR_VIDEO";
}