package grest.dfareporting.v3.5.types;
@:enum abstract Api_ChangeLogs_list_action(String) from String to String to tink.Stringly {
	var ACTION_ADD = "ACTION_ADD";
	var ACTION_ASSIGN = "ACTION_ASSIGN";
	var ACTION_ASSOCIATE = "ACTION_ASSOCIATE";
	var ACTION_CREATE = "ACTION_CREATE";
	var ACTION_DELETE = "ACTION_DELETE";
	var ACTION_DISABLE = "ACTION_DISABLE";
	var ACTION_EMAIL_TAGS = "ACTION_EMAIL_TAGS";
	var ACTION_ENABLE = "ACTION_ENABLE";
	var ACTION_LINK = "ACTION_LINK";
	var ACTION_MARK_AS_DEFAULT = "ACTION_MARK_AS_DEFAULT";
	var ACTION_PUSH = "ACTION_PUSH";
	var ACTION_REMOVE = "ACTION_REMOVE";
	var ACTION_SEND = "ACTION_SEND";
	var ACTION_SHARE = "ACTION_SHARE";
	var ACTION_UNASSIGN = "ACTION_UNASSIGN";
	var ACTION_UNLINK = "ACTION_UNLINK";
	var ACTION_UPDATE = "ACTION_UPDATE";
}