package grest.dfareporting.v3.5.types;
@:enum abstract Api_Placements_generatetags_tagFormats(String) from String to String to tink.Stringly {
	var PLACEMENT_TAG_CLICK_COMMANDS = "PLACEMENT_TAG_CLICK_COMMANDS";
	var PLACEMENT_TAG_IFRAME_ILAYER = "PLACEMENT_TAG_IFRAME_ILAYER";
	var PLACEMENT_TAG_IFRAME_JAVASCRIPT = "PLACEMENT_TAG_IFRAME_JAVASCRIPT";
	var PLACEMENT_TAG_IFRAME_JAVASCRIPT_LEGACY = "PLACEMENT_TAG_IFRAME_JAVASCRIPT_LEGACY";
	var PLACEMENT_TAG_INSTREAM_VIDEO_PREFETCH = "PLACEMENT_TAG_INSTREAM_VIDEO_PREFETCH";
	var PLACEMENT_TAG_INSTREAM_VIDEO_PREFETCH_VAST_3 = "PLACEMENT_TAG_INSTREAM_VIDEO_PREFETCH_VAST_3";
	var PLACEMENT_TAG_INSTREAM_VIDEO_PREFETCH_VAST_4 = "PLACEMENT_TAG_INSTREAM_VIDEO_PREFETCH_VAST_4";
	var PLACEMENT_TAG_INTERNAL_REDIRECT = "PLACEMENT_TAG_INTERNAL_REDIRECT";
	var PLACEMENT_TAG_INTERSTITIAL_IFRAME_JAVASCRIPT = "PLACEMENT_TAG_INTERSTITIAL_IFRAME_JAVASCRIPT";
	var PLACEMENT_TAG_INTERSTITIAL_IFRAME_JAVASCRIPT_LEGACY = "PLACEMENT_TAG_INTERSTITIAL_IFRAME_JAVASCRIPT_LEGACY";
	var PLACEMENT_TAG_INTERSTITIAL_INTERNAL_REDIRECT = "PLACEMENT_TAG_INTERSTITIAL_INTERNAL_REDIRECT";
	var PLACEMENT_TAG_INTERSTITIAL_JAVASCRIPT = "PLACEMENT_TAG_INTERSTITIAL_JAVASCRIPT";
	var PLACEMENT_TAG_INTERSTITIAL_JAVASCRIPT_LEGACY = "PLACEMENT_TAG_INTERSTITIAL_JAVASCRIPT_LEGACY";
	var PLACEMENT_TAG_JAVASCRIPT = "PLACEMENT_TAG_JAVASCRIPT";
	var PLACEMENT_TAG_JAVASCRIPT_LEGACY = "PLACEMENT_TAG_JAVASCRIPT_LEGACY";
	var PLACEMENT_TAG_STANDARD = "PLACEMENT_TAG_STANDARD";
	var PLACEMENT_TAG_TRACKING = "PLACEMENT_TAG_TRACKING";
	var PLACEMENT_TAG_TRACKING_IFRAME = "PLACEMENT_TAG_TRACKING_IFRAME";
	var PLACEMENT_TAG_TRACKING_JAVASCRIPT = "PLACEMENT_TAG_TRACKING_JAVASCRIPT";
}