package grest.dfareporting.v3.5.types;
typedef CreativeAsset = {
	/**
		Whether ActionScript3 is enabled for the flash asset. This is a read-only field. Applicable to the following creative type: FLASH_INPAGE. Applicable to DISPLAY when the primary asset type is not HTML_IMAGE.
	**/
	@:optional
	var actionScript3 : Bool;
	/**
		Whether the video or audio asset is active. This is a read-only field for VPAID_NON_LINEAR_VIDEO assets. Applicable to the following creative types: INSTREAM_AUDIO, INSTREAM_VIDEO and all VPAID.
	**/
	@:optional
	var active : Bool;
	/**
		Additional sizes associated with this creative asset. HTML5 asset generated by compatible software such as GWD will be able to support more sizes this creative asset can render.
	**/
	@:optional
	var additionalSizes : Array<Size>;
	/**
		Possible alignments for an asset. This is a read-only field. Applicable to the following creative types: RICH_MEDIA_DISPLAY_MULTI_FLOATING_INTERSTITIAL .
	**/
	@:optional
	var alignment : grest.dfareporting.v3.5.types.CreativeAsset_alignment;
	/**
		Artwork type of rich media creative. This is a read-only field. Applicable to the following creative types: all RICH_MEDIA.
	**/
	@:optional
	var artworkType : grest.dfareporting.v3.5.types.CreativeAsset_artworkType;
	/**
		Identifier of this asset. This is the same identifier returned during creative asset insert operation. This is a required field. Applicable to all but the following creative types: all REDIRECT and TRACKING_TEXT.
	**/
	@:optional
	var assetIdentifier : CreativeAssetId;
	/**
		Audio stream bit rate in kbps. This is a read-only field. Applicable to the following creative types: INSTREAM_AUDIO, INSTREAM_VIDEO and all VPAID.
	**/
	@:optional
	var audioBitRate : Int;
	/**
		Audio sample bit rate in hertz. This is a read-only field. Applicable to the following creative types: INSTREAM_AUDIO, INSTREAM_VIDEO and all VPAID.
	**/
	@:optional
	var audioSampleRate : Int;
	/**
		Exit event configured for the backup image. Applicable to the following creative types: all RICH_MEDIA.
	**/
	@:optional
	var backupImageExit : CreativeCustomEvent;
	/**
		Detected bit-rate for audio or video asset. This is a read-only field. Applicable to the following creative types: INSTREAM_AUDIO, INSTREAM_VIDEO and all VPAID.
	**/
	@:optional
	var bitRate : Int;
	/**
		Rich media child asset type. This is a read-only field. Applicable to the following creative types: all VPAID.
	**/
	@:optional
	var childAssetType : grest.dfareporting.v3.5.types.CreativeAsset_childAssetType;
	/**
		Size of an asset when collapsed. This is a read-only field. Applicable to the following creative types: all RICH_MEDIA and all VPAID. Additionally, applicable to assets whose displayType is ASSET_DISPLAY_TYPE_EXPANDING or ASSET_DISPLAY_TYPE_PEEL_DOWN.
	**/
	@:optional
	var collapsedSize : Size;
	/**
		List of companion creatives assigned to an in-stream video creative asset. Acceptable values include IDs of existing flash and image creatives. Applicable to INSTREAM_VIDEO creative type with dynamicAssetSelection set to true.
	**/
	@:optional
	var companionCreativeIds : Array<String>;
	/**
		Custom start time in seconds for making the asset visible. Applicable to the following creative types: all RICH_MEDIA. Value must be greater than or equal to 0.
	**/
	@:optional
	var customStartTimeValue : Int;
	/**
		List of feature dependencies for the creative asset that are detected by Campaign Manager. Feature dependencies are features that a browser must be able to support in order to render your HTML5 creative correctly. This is a read-only, auto-generated field. Applicable to the following creative types: HTML5_BANNER. Applicable to DISPLAY when the primary asset type is not HTML_IMAGE.
	**/
	@:optional
	var detectedFeatures : Array<String>;
	/**
		Type of rich media asset. This is a read-only field. Applicable to the following creative types: all RICH_MEDIA.
	**/
	@:optional
	var displayType : grest.dfareporting.v3.5.types.CreativeAsset_displayType;
	/**
		Duration in seconds for which an asset will be displayed. Applicable to the following creative types: INSTREAM_AUDIO, INSTREAM_VIDEO and VPAID_LINEAR_VIDEO. Value must be greater than or equal to 1.
	**/
	@:optional
	var duration : Int;
	/**
		Duration type for which an asset will be displayed. Applicable to the following creative types: all RICH_MEDIA.
	**/
	@:optional
	var durationType : grest.dfareporting.v3.5.types.CreativeAsset_durationType;
	/**
		Detected expanded dimension for video asset. This is a read-only field. Applicable to the following creative types: INSTREAM_VIDEO and all VPAID.
	**/
	@:optional
	var expandedDimension : Size;
	/**
		File size associated with this creative asset. This is a read-only field. Applicable to all but the following creative types: all REDIRECT and TRACKING_TEXT.
	**/
	@:optional
	var fileSize : String;
	/**
		Flash version of the asset. This is a read-only field. Applicable to the following creative types: FLASH_INPAGE, all RICH_MEDIA, and all VPAID. Applicable to DISPLAY when the primary asset type is not HTML_IMAGE.
	**/
	@:optional
	var flashVersion : Int;
	/**
		Video frame rate for video asset in frames per second. This is a read-only field. Applicable to the following creative types: INSTREAM_VIDEO and all VPAID.
	**/
	@:optional
	var frameRate : Float;
	/**
		Whether to hide Flash objects flag for an asset. Applicable to the following creative types: all RICH_MEDIA.
	**/
	@:optional
	var hideFlashObjects : Bool;
	/**
		Whether to hide selection boxes flag for an asset. Applicable to the following creative types: all RICH_MEDIA.
	**/
	@:optional
	var hideSelectionBoxes : Bool;
	/**
		Whether the asset is horizontally locked. This is a read-only field. Applicable to the following creative types: all RICH_MEDIA.
	**/
	@:optional
	var horizontallyLocked : Bool;
	/**
		Numeric ID of this creative asset. This is a required field and should not be modified. Applicable to all but the following creative types: all REDIRECT and TRACKING_TEXT.
	**/
	@:optional
	var id : String;
	/**
		Dimension value for the ID of the asset. This is a read-only, auto-generated field.
	**/
	@:optional
	var idDimensionValue : DimensionValue;
	/**
		Detected duration for audio or video asset. This is a read-only field. Applicable to the following creative types: INSTREAM_AUDIO, INSTREAM_VIDEO and all VPAID.
	**/
	@:optional
	var mediaDuration : Float;
	/**
		Detected MIME type for audio or video asset. This is a read-only field. Applicable to the following creative types: INSTREAM_AUDIO, INSTREAM_VIDEO and all VPAID.
	**/
	@:optional
	var mimeType : String;
	/**
		Offset position for an asset in collapsed mode. This is a read-only field. Applicable to the following creative types: all RICH_MEDIA and all VPAID. Additionally, only applicable to assets whose displayType is ASSET_DISPLAY_TYPE_EXPANDING or ASSET_DISPLAY_TYPE_PEEL_DOWN.
	**/
	@:optional
	var offset : OffsetPosition;
	/**
		Orientation of video asset. This is a read-only, auto-generated field.
	**/
	@:optional
	var orientation : grest.dfareporting.v3.5.types.CreativeAsset_orientation;
	/**
		Whether the backup asset is original or changed by the user in Campaign Manager. Applicable to the following creative types: all RICH_MEDIA.
	**/
	@:optional
	var originalBackup : Bool;
	/**
		Whether this asset is used as a polite load asset.
	**/
	@:optional
	var politeLoad : Bool;
	/**
		Offset position for an asset. Applicable to the following creative types: all RICH_MEDIA.
	**/
	@:optional
	var position : OffsetPosition;
	/**
		Offset left unit for an asset. This is a read-only field. Applicable to the following creative types: all RICH_MEDIA.
	**/
	@:optional
	var positionLeftUnit : grest.dfareporting.v3.5.types.CreativeAsset_positionLeftUnit;
	/**
		Offset top unit for an asset. This is a read-only field if the asset displayType is ASSET_DISPLAY_TYPE_OVERLAY. Applicable to the following creative types: all RICH_MEDIA.
	**/
	@:optional
	var positionTopUnit : grest.dfareporting.v3.5.types.CreativeAsset_positionTopUnit;
	/**
		Progressive URL for video asset. This is a read-only field. Applicable to the following creative types: INSTREAM_VIDEO and all VPAID.
	**/
	@:optional
	var progressiveServingUrl : String;
	/**
		Whether the asset pushes down other content. Applicable to the following creative types: all RICH_MEDIA. Additionally, only applicable when the asset offsets are 0, the collapsedSize.width matches size.width, and the collapsedSize.height is less than size.height.
	**/
	@:optional
	var pushdown : Bool;
	/**
		Pushdown duration in seconds for an asset. Applicable to the following creative types: all RICH_MEDIA.Additionally, only applicable when the asset pushdown field is true, the offsets are 0, the collapsedSize.width matches size.width, and the collapsedSize.height is less than size.height. Acceptable values are 0 to 9.99, inclusive.
	**/
	@:optional
	var pushdownDuration : Float;
	/**
		Role of the asset in relation to creative. Applicable to all but the following creative types: all REDIRECT and TRACKING_TEXT. This is a required field. PRIMARY applies to DISPLAY, FLASH_INPAGE, HTML5_BANNER, IMAGE, DISPLAY_IMAGE_GALLERY, all RICH_MEDIA (which may contain multiple primary assets), and all VPAID creatives. BACKUP_IMAGE applies to FLASH_INPAGE, HTML5_BANNER, all RICH_MEDIA, and all VPAID creatives. Applicable to DISPLAY when the primary asset type is not HTML_IMAGE. ADDITIONAL_IMAGE and ADDITIONAL_FLASH apply to FLASH_INPAGE creatives. OTHER refers to assets from sources other than Campaign Manager, such as Studio uploaded assets, applicable to all RICH_MEDIA and all VPAID creatives. PARENT_VIDEO refers to videos uploaded by the user in Campaign Manager and is applicable to INSTREAM_VIDEO and VPAID_LINEAR_VIDEO creatives. TRANSCODED_VIDEO refers to videos transcoded by Campaign Manager from PARENT_VIDEO assets and is applicable to INSTREAM_VIDEO and VPAID_LINEAR_VIDEO creatives. ALTERNATE_VIDEO refers to the Campaign Manager representation of child asset videos from Studio, and is applicable to VPAID_LINEAR_VIDEO creatives. These cannot be added or removed within Campaign Manager. For VPAID_LINEAR_VIDEO creatives, PARENT_VIDEO, TRANSCODED_VIDEO and ALTERNATE_VIDEO assets that are marked active serve as backup in case the VPAID creative cannot be served. Only PARENT_VIDEO assets can be added or removed for an INSTREAM_VIDEO or VPAID_LINEAR_VIDEO creative. PARENT_AUDIO refers to audios uploaded by the user in Campaign Manager and is applicable to INSTREAM_AUDIO creatives. TRANSCODED_AUDIO refers to audios transcoded by Campaign Manager from PARENT_AUDIO assets and is applicable to INSTREAM_AUDIO creatives. 
	**/
	@:optional
	var role : grest.dfareporting.v3.5.types.CreativeAsset_role;
	/**
		Size associated with this creative asset. This is a required field when applicable; however for IMAGE and FLASH_INPAGE, creatives if left blank, this field will be automatically set using the actual size of the associated image asset. Applicable to the following creative types: DISPLAY_IMAGE_GALLERY, FLASH_INPAGE, HTML5_BANNER, IMAGE, and all RICH_MEDIA. Applicable to DISPLAY when the primary asset type is not HTML_IMAGE.
	**/
	@:optional
	var size : Size;
	/**
		Whether the asset is SSL-compliant. This is a read-only field. Applicable to all but the following creative types: all REDIRECT and TRACKING_TEXT.
	**/
	@:optional
	var sslCompliant : Bool;
	/**
		Initial wait time type before making the asset visible. Applicable to the following creative types: all RICH_MEDIA.
	**/
	@:optional
	var startTimeType : grest.dfareporting.v3.5.types.CreativeAsset_startTimeType;
	/**
		Streaming URL for video asset. This is a read-only field. Applicable to the following creative types: INSTREAM_VIDEO and all VPAID.
	**/
	@:optional
	var streamingServingUrl : String;
	/**
		Whether the asset is transparent. Applicable to the following creative types: all RICH_MEDIA. Additionally, only applicable to HTML5 assets.
	**/
	@:optional
	var transparency : Bool;
	/**
		Whether the asset is vertically locked. This is a read-only field. Applicable to the following creative types: all RICH_MEDIA.
	**/
	@:optional
	var verticallyLocked : Bool;
	/**
		Window mode options for flash assets. Applicable to the following creative types: FLASH_INPAGE, RICH_MEDIA_DISPLAY_EXPANDING, RICH_MEDIA_IM_EXPAND, RICH_MEDIA_DISPLAY_BANNER, and RICH_MEDIA_INPAGE_FLOATING.
	**/
	@:optional
	var windowMode : grest.dfareporting.v3.5.types.CreativeAsset_windowMode;
	/**
		zIndex value of an asset. Applicable to the following creative types: all RICH_MEDIA.Additionally, only applicable to assets whose displayType is NOT one of the following types: ASSET_DISPLAY_TYPE_INPAGE or ASSET_DISPLAY_TYPE_OVERLAY. Acceptable values are -999999999 to 999999999, inclusive.
	**/
	@:optional
	var zIndex : Int;
	/**
		File name of zip file. This is a read-only field. Applicable to the following creative types: HTML5_BANNER.
	**/
	@:optional
	var zipFilename : String;
	/**
		Size of zip file. This is a read-only field. Applicable to the following creative types: HTML5_BANNER.
	**/
	@:optional
	var zipFilesize : String;
}