package grest.dfareporting.v3.5.types;
@:enum abstract CreativeAsset_displayType(String) from String to String to tink.Stringly {
	var ASSET_DISPLAY_TYPE_BACKDROP = "ASSET_DISPLAY_TYPE_BACKDROP";
	var ASSET_DISPLAY_TYPE_EXPANDING = "ASSET_DISPLAY_TYPE_EXPANDING";
	var ASSET_DISPLAY_TYPE_FLASH_IN_FLASH = "ASSET_DISPLAY_TYPE_FLASH_IN_FLASH";
	var ASSET_DISPLAY_TYPE_FLASH_IN_FLASH_EXPANDING = "ASSET_DISPLAY_TYPE_FLASH_IN_FLASH_EXPANDING";
	var ASSET_DISPLAY_TYPE_FLOATING = "ASSET_DISPLAY_TYPE_FLOATING";
	var ASSET_DISPLAY_TYPE_INPAGE = "ASSET_DISPLAY_TYPE_INPAGE";
	var ASSET_DISPLAY_TYPE_OVERLAY = "ASSET_DISPLAY_TYPE_OVERLAY";
	var ASSET_DISPLAY_TYPE_PEEL_DOWN = "ASSET_DISPLAY_TYPE_PEEL_DOWN";
	var ASSET_DISPLAY_TYPE_VPAID_LINEAR = "ASSET_DISPLAY_TYPE_VPAID_LINEAR";
	var ASSET_DISPLAY_TYPE_VPAID_NON_LINEAR = "ASSET_DISPLAY_TYPE_VPAID_NON_LINEAR";
}