package grest.dfareporting.v3.5.types;
@:enum abstract Creative_authoringSource(String) from String to String to tink.Stringly {
	var CREATIVE_AUTHORING_SOURCE_DBM = "CREATIVE_AUTHORING_SOURCE_DBM";
	var CREATIVE_AUTHORING_SOURCE_DCM = "CREATIVE_AUTHORING_SOURCE_DCM";
	var CREATIVE_AUTHORING_SOURCE_GWD = "CREATIVE_AUTHORING_SOURCE_GWD";
	var CREATIVE_AUTHORING_SOURCE_STUDIO = "CREATIVE_AUTHORING_SOURCE_STUDIO";
}