package grest.dfareporting.v3.5.types;
@:enum abstract FloodlightConfiguration_naturalSearchConversionAttributionOption(String) from String to String to tink.Stringly {
	var EXCLUDE_NATURAL_SEARCH_CONVERSION_ATTRIBUTION = "EXCLUDE_NATURAL_SEARCH_CONVERSION_ATTRIBUTION";
	var INCLUDE_NATURAL_SEARCH_CONVERSION_ATTRIBUTION = "INCLUDE_NATURAL_SEARCH_CONVERSION_ATTRIBUTION";
	var INCLUDE_NATURAL_SEARCH_TIERED_CONVERSION_ATTRIBUTION = "INCLUDE_NATURAL_SEARCH_TIERED_CONVERSION_ATTRIBUTION";
}