package grest.dfareporting.v3.5.types;
@:enum abstract MeasurementPartnerCampaignLink_linkStatus(String) from String to String to tink.Stringly {
	var MEASUREMENT_PARTNER_LINKED = "MEASUREMENT_PARTNER_LINKED";
	var MEASUREMENT_PARTNER_LINK_FAILURE = "MEASUREMENT_PARTNER_LINK_FAILURE";
	var MEASUREMENT_PARTNER_LINK_OPT_OUT = "MEASUREMENT_PARTNER_LINK_OPT_OUT";
	var MEASUREMENT_PARTNER_LINK_OPT_OUT_PENDING = "MEASUREMENT_PARTNER_LINK_OPT_OUT_PENDING";
	var MEASUREMENT_PARTNER_LINK_PENDING = "MEASUREMENT_PARTNER_LINK_PENDING";
	var MEASUREMENT_PARTNER_LINK_WRAPPING_PENDING = "MEASUREMENT_PARTNER_LINK_WRAPPING_PENDING";
	var MEASUREMENT_PARTNER_MODE_CHANGE_PENDING = "MEASUREMENT_PARTNER_MODE_CHANGE_PENDING";
	var MEASUREMENT_PARTNER_UNLINKED = "MEASUREMENT_PARTNER_UNLINKED";
}