package grest.dfareporting.v3.5.types;
@:enum abstract OrderContact_contactType(String) from String to String to tink.Stringly {
	var PLANNING_ORDER_CONTACT_BUYER_BILLING_CONTACT = "PLANNING_ORDER_CONTACT_BUYER_BILLING_CONTACT";
	var PLANNING_ORDER_CONTACT_BUYER_CONTACT = "PLANNING_ORDER_CONTACT_BUYER_CONTACT";
	var PLANNING_ORDER_CONTACT_SELLER_CONTACT = "PLANNING_ORDER_CONTACT_SELLER_CONTACT";
}