package grest.dfareporting.v3.5.types;
@:enum abstract Pricing_pricingType(String) from String to String to tink.Stringly {
	var PLANNING_PLACEMENT_PRICING_TYPE_CLICKS = "PLANNING_PLACEMENT_PRICING_TYPE_CLICKS";
	var PLANNING_PLACEMENT_PRICING_TYPE_CPA = "PLANNING_PLACEMENT_PRICING_TYPE_CPA";
	var PLANNING_PLACEMENT_PRICING_TYPE_CPC = "PLANNING_PLACEMENT_PRICING_TYPE_CPC";
	var PLANNING_PLACEMENT_PRICING_TYPE_CPM = "PLANNING_PLACEMENT_PRICING_TYPE_CPM";
	var PLANNING_PLACEMENT_PRICING_TYPE_CPM_ACTIVEVIEW = "PLANNING_PLACEMENT_PRICING_TYPE_CPM_ACTIVEVIEW";
	var PLANNING_PLACEMENT_PRICING_TYPE_FLAT_RATE_CLICKS = "PLANNING_PLACEMENT_PRICING_TYPE_FLAT_RATE_CLICKS";
	var PLANNING_PLACEMENT_PRICING_TYPE_FLAT_RATE_IMPRESSIONS = "PLANNING_PLACEMENT_PRICING_TYPE_FLAT_RATE_IMPRESSIONS";
	var PLANNING_PLACEMENT_PRICING_TYPE_IMPRESSIONS = "PLANNING_PLACEMENT_PRICING_TYPE_IMPRESSIONS";
}