package grest.dfareporting.v3.5.types;
@:enum abstract Pricing_capCostType(String) from String to String to tink.Stringly {
	var PLANNING_PLACEMENT_CAP_COST_TYPE_CUMULATIVE = "PLANNING_PLACEMENT_CAP_COST_TYPE_CUMULATIVE";
	var PLANNING_PLACEMENT_CAP_COST_TYPE_MONTHLY = "PLANNING_PLACEMENT_CAP_COST_TYPE_MONTHLY";
	var PLANNING_PLACEMENT_CAP_COST_TYPE_NONE = "PLANNING_PLACEMENT_CAP_COST_TYPE_NONE";
}