package grest.dfareporting.v3.5.types;
@:enum abstract Project_audienceAgeGroup(String) from String to String to tink.Stringly {
	var PLANNING_AUDIENCE_AGE_18_24 = "PLANNING_AUDIENCE_AGE_18_24";
	var PLANNING_AUDIENCE_AGE_25_34 = "PLANNING_AUDIENCE_AGE_25_34";
	var PLANNING_AUDIENCE_AGE_35_44 = "PLANNING_AUDIENCE_AGE_35_44";
	var PLANNING_AUDIENCE_AGE_45_54 = "PLANNING_AUDIENCE_AGE_45_54";
	var PLANNING_AUDIENCE_AGE_55_64 = "PLANNING_AUDIENCE_AGE_55_64";
	var PLANNING_AUDIENCE_AGE_65_OR_MORE = "PLANNING_AUDIENCE_AGE_65_OR_MORE";
	var PLANNING_AUDIENCE_AGE_UNKNOWN = "PLANNING_AUDIENCE_AGE_UNKNOWN";
}