package grest.dfareporting.v3.5.types;
@:enum abstract TargetableRemarketingList_listSource(String) from String to String to tink.Stringly {
	var REMARKETING_LIST_SOURCE_ADX = "REMARKETING_LIST_SOURCE_ADX";
	var REMARKETING_LIST_SOURCE_DBM = "REMARKETING_LIST_SOURCE_DBM";
	var REMARKETING_LIST_SOURCE_DFA = "REMARKETING_LIST_SOURCE_DFA";
	var REMARKETING_LIST_SOURCE_DFP = "REMARKETING_LIST_SOURCE_DFP";
	var REMARKETING_LIST_SOURCE_DMP = "REMARKETING_LIST_SOURCE_DMP";
	var REMARKETING_LIST_SOURCE_GA = "REMARKETING_LIST_SOURCE_GA";
	var REMARKETING_LIST_SOURCE_GPLUS = "REMARKETING_LIST_SOURCE_GPLUS";
	var REMARKETING_LIST_SOURCE_OTHER = "REMARKETING_LIST_SOURCE_OTHER";
	var REMARKETING_LIST_SOURCE_PLAY_STORE = "REMARKETING_LIST_SOURCE_PLAY_STORE";
	var REMARKETING_LIST_SOURCE_XFP = "REMARKETING_LIST_SOURCE_XFP";
	var REMARKETING_LIST_SOURCE_YOUTUBE = "REMARKETING_LIST_SOURCE_YOUTUBE";
}