package grest.dfareporting.v3.5.types;
@:enum abstract ThirdPartyTrackingUrl_thirdPartyUrlType(String) from String to String to tink.Stringly {
	var CLICK_TRACKING = "CLICK_TRACKING";
	var IMPRESSION = "IMPRESSION";
	var RICH_MEDIA_BACKUP_IMPRESSION = "RICH_MEDIA_BACKUP_IMPRESSION";
	var RICH_MEDIA_IMPRESSION = "RICH_MEDIA_IMPRESSION";
	var RICH_MEDIA_RM_IMPRESSION = "RICH_MEDIA_RM_IMPRESSION";
	var SURVEY = "SURVEY";
	var VIDEO_COMPLETE = "VIDEO_COMPLETE";
	var VIDEO_CUSTOM = "VIDEO_CUSTOM";
	var VIDEO_FIRST_QUARTILE = "VIDEO_FIRST_QUARTILE";
	var VIDEO_FULLSCREEN = "VIDEO_FULLSCREEN";
	var VIDEO_MIDPOINT = "VIDEO_MIDPOINT";
	var VIDEO_MUTE = "VIDEO_MUTE";
	var VIDEO_PAUSE = "VIDEO_PAUSE";
	var VIDEO_PROGRESS = "VIDEO_PROGRESS";
	var VIDEO_REWIND = "VIDEO_REWIND";
	var VIDEO_SKIP = "VIDEO_SKIP";
	var VIDEO_START = "VIDEO_START";
	var VIDEO_STOP = "VIDEO_STOP";
	var VIDEO_THIRD_QUARTILE = "VIDEO_THIRD_QUARTILE";
}