package grest.dfareporting.v3.5.types;
@:enum abstract UserRolePermission_availability(String) from String to String to tink.Stringly {
	var ACCOUNT_ALWAYS = "ACCOUNT_ALWAYS";
	var ACCOUNT_BY_DEFAULT = "ACCOUNT_BY_DEFAULT";
	var NOT_AVAILABLE_BY_DEFAULT = "NOT_AVAILABLE_BY_DEFAULT";
	var SUBACCOUNT_AND_ACCOUNT_ALWAYS = "SUBACCOUNT_AND_ACCOUNT_ALWAYS";
	var SUBACCOUNT_AND_ACCOUNT_BY_DEFAULT = "SUBACCOUNT_AND_ACCOUNT_BY_DEFAULT";
	var USER_PROFILE_ONLY = "USER_PROFILE_ONLY";
}