package grest.clouddebugger.v2.types;
@:enum abstract Debuggee_canaryMode(String) from String to String to tink.Stringly {
	var CANARY_MODE_ALWAYS_DISABLED = "CANARY_MODE_ALWAYS_DISABLED";
	var CANARY_MODE_ALWAYS_ENABLED = "CANARY_MODE_ALWAYS_ENABLED";
	var CANARY_MODE_DEFAULT_DISABLED = "CANARY_MODE_DEFAULT_DISABLED";
	var CANARY_MODE_DEFAULT_ENABLED = "CANARY_MODE_DEFAULT_ENABLED";
	var CANARY_MODE_UNSPECIFIED = "CANARY_MODE_UNSPECIFIED";
}