package grest.clouddebugger.v2.types;
@:enum abstract StatusMessage_refersTo(String) from String to String to tink.Stringly {
	var BREAKPOINT_AGE = "BREAKPOINT_AGE";
	var BREAKPOINT_CANARY_FAILED = "BREAKPOINT_CANARY_FAILED";
	var BREAKPOINT_CONDITION = "BREAKPOINT_CONDITION";
	var BREAKPOINT_EXPRESSION = "BREAKPOINT_EXPRESSION";
	var BREAKPOINT_SOURCE_LOCATION = "BREAKPOINT_SOURCE_LOCATION";
	var UNSPECIFIED = "UNSPECIFIED";
	var VARIABLE_NAME = "VARIABLE_NAME";
	var VARIABLE_VALUE = "VARIABLE_VALUE";
}