name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        haxe-version:
          - 4.0.5
          - 4.1.5
          - stable
          - nightly
        target: 
          - interp
          - node
          - node -D tink_core_no_error_pos
          - neko
          - python
          - php
          - cpp
          - js
          - java -D jvm
          - cs -D erase-generics
        exclude:
          - haxe-version: 4.0.5
            target: java -D jvm

    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache Yarn
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
        
    - name: Cache Haxe
      uses: actions/cache@v1
      with:
        path: ${{ startsWith(runner.os, 'windows') && '%AppData%' || '~/haxe' }}
        key: ${{ runner.os }}-haxe
        
    - name: Install Lix
      uses: lix-pm/setup-lix@master
      
    - name: Install Haxe
      run: lix install haxe ${{ matrix.haxe-version }}
    
    - name: Install Haxe Libraries
      run: lix download
      
    - name: Run Test
      run: lix run travix ${{ matrix.target }}
